import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const levelsData = [
  {
    level_id: 51,
    title: 'Level 51: Vocabulary',
    unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)',
    category: 'Vocabulary',
    items: [
      {
        id: 251,
        word: 'Profound',
        ipa: '/prəˈfaʊnd/',
        pos: 'adj',
        meaning: 'গভীর, সুদূরপ্রসারী ও তাৎপর্যপূর্ণ',
        synonyms: ['deep', 'insightful', 'intense', 'far-reaching'],
        antonyms: ['superficial', 'shallow', 'trivial', 'slight'],
        raw_synonyms: 'deep, insightful, intense, far-reaching',
        raw_antonyms: 'superficial, shallow, trivial, slight',
        sentence: 'The philosophical lecture made a profound impact on the students\' intellectual outlook.',
        sentence_meaning: 'দার্শনিক বক্তৃতাটি শিক্ষার্থীদের বুদ্ধিবৃত্তিক দৃষ্টিভঙ্গির ওপর এক গভীর প্রভাব ফেলেছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 252,
        word: 'Trend',
        ipa: '/trend/',
        pos: 'n',
        meaning: 'প্রবণতা, ধারা বা গতিপ্রকৃতি',
        synonyms: ['tendency', 'pattern', 'movement', 'vogue'],
        antonyms: ['stagnation', 'aberration', 'irregularity', 'anomaly'],
        raw_synonyms: 'tendency, pattern, movement, vogue',
        raw_antonyms: 'stagnation, aberration, irregularity, anomaly',
        sentence: 'There is a noticeable global trend towards renewable energy and sustainable consumption.',
        sentence_meaning: 'নবায়নযোগ্য জ্বালানি এবং টেকসই ব্যবহারের দিকে একটি লক্ষণীয় বৈশ্বিক প্রবণতা রয়েছে।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 253,
        word: 'Expressionism',
        ipa: '/ɪkˈspreʃənɪzəm/',
        pos: 'n',
        meaning: 'অভিব্যক্তিবাদ (শিল্পকলা ও সাহিত্যের এক বিশিষ্ট ধারা)',
        synonyms: ['modernist movement', 'symbolic art', 'emotive realism', 'subjective style'],
        antonyms: ['naturalism', 'photorealism', 'strict classicism'],
        raw_synonyms: 'modernist movement, symbolic art, emotive realism, subjective style',
        raw_antonyms: 'naturalism, photorealism, strict classicism',
        sentence: 'German expressionism in early twentieth-century painting emphasized raw emotional reality over realistic accuracy.',
        sentence_meaning: 'বিংশ শতাব্দীর শুরুর দিকের চিত্রশিল্পে জার্মান অভিব্যক্তিবাদ বাস্তবসম্মত নিখুঁততার চেয়ে তীব্র আবেগীয় বাস্তবতাকে বেশি গুরুত্ব দিয়েছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 254,
        word: 'Haunting',
        ipa: '/ˈhɔːntɪŋ/',
        pos: 'adj',
        meaning: 'ভুলতে না পারা, মনে দাগ কাটার মতো মর্মস্পর্শী',
        synonyms: ['evocative', 'unforgettable', 'poignant', 'memorable'],
        antonyms: ['forgettable', 'uninspiring', 'bland', 'fleeting'],
        raw_synonyms: 'evocative, unforgettable, poignant, memorable',
        raw_antonyms: 'forgettable, uninspiring, bland, fleeting',
        sentence: 'The vocalist sang a haunting melody that resonated deeply in the hearts of the listeners.',
        sentence_meaning: 'কণ্ঠশিল্পী এমন একটি অবিস্মরণীয় সুর গেয়েছিলেন যা শ্রোতাদের হৃদয়ে গভীরভাবে আলোড়ন সৃষ্টি করেছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 255,
        word: 'Prominent',
        ipa: '/ˈprɑːmɪnənt/',
        pos: 'adj',
        meaning: 'বিশিষ্ট, খ্যাতিমান ও চোখে পড়ার মতো',
        synonyms: ['distinguished', 'conspicuous', 'renowned', 'notable'],
        antonyms: ['obscure', 'inconspicuous', 'unknown', 'insignificant'],
        raw_synonyms: 'distinguished, conspicuous, renowned, notable',
        raw_antonyms: 'obscure, inconspicuous, unknown, insignificant',
        sentence: 'Several prominent scientists attended the international symposium on artificial intelligence.',
        sentence_meaning: 'কৃত্রিম বুদ্ধিমত্তা বিষয়ক আন্তর্জাতিক সম্মেলনে বেশ কয়েকজন বিশিষ্ট বিজ্ঞানী উপস্থিত ছিলেন।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      }
    ]
  },
  {
    level_id: 52,
    title: 'Level 52: Vocabulary',
    unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)',
    category: 'Vocabulary',
    items: [
      {
        id: 256,
        word: 'Spectacular',
        ipa: '/spekˈtækjələr/',
        pos: 'adj',
        meaning: 'দর্শনীয়, নয়নাভিরাম ও চমকপ্রদ',
        synonyms: ['magnificent', 'breathtaking', 'splendid', 'stunning'],
        antonyms: ['unimpressive', 'ordinary', 'mediocre', 'dull'],
        raw_synonyms: 'magnificent, breathtaking, splendid, stunning',
        raw_antonyms: 'unimpressive, ordinary, mediocre, dull',
        sentence: 'The midnight fireworks display over the harbor was a truly spectacular sight to behold.',
        sentence_meaning: 'পোতাশ্রয়ের ওপর মধ্যরাতের আতশবাজির প্রদর্শনীটি সত্যিই এক অসাধারণ দর্শনীয় দৃশ্য ছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 257,
        word: 'Contemporary',
        ipa: '/kənˈtempəreri/',
        pos: 'adj',
        meaning: 'সমসাময়িক, আধুনিক',
        synonyms: ['modern', 'present-day', 'current', 'coexistent'],
        antonyms: ['ancient', 'archaic', 'outdated', 'traditional'],
        raw_synonyms: 'modern, present-day, current, coexistent',
        raw_antonyms: 'ancient, archaic, outdated, traditional',
        sentence: 'Contemporary literature reflects the multifaceted social and technological dilemmas of the twenty-first century.',
        sentence_meaning: 'সমসাময়িক সাহিত্য একবিংশ শতাব্দীর বহুমুখী সামাজিক ও প্রযুক্তিগত সংকটগুলোকে প্রতিফলিত করে।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 258,
        word: 'Explore',
        ipa: '/ɪkˈsplɔːr/',
        pos: 'v',
        meaning: 'অন্বেষণ করা, বিশদভাবে খতিয়ে দেখা',
        synonyms: ['investigate', 'examine', 'probe', 'delve into'],
        antonyms: ['neglect', 'overlook', 'ignore', 'disregard'],
        raw_synonyms: 'investigate, examine, probe, delve into',
        raw_antonyms: 'neglect, overlook, ignore, disregard',
        sentence: 'The seminar aimed to explore novel methodologies for combating climate change in coastal zones.',
        sentence_meaning: 'সেমিনারটির লক্ষ্য ছিল উপকূলীয় অঞ্চলে জলবায়ু পরিবর্তন মোকাবিলার জন্য নতুন কার্যপদ্ধতি অন্বেষণ করা।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 259,
        word: 'Expressive',
        ipa: '/ɪkˈspresɪv/',
        pos: 'adj',
        meaning: 'ভাবব্যঞ্জক, অনুভূতি স্পষ্টভাবে প্রকাশ করে এমন',
        synonyms: ['evocative', 'eloquent', 'revealing', 'meaningful'],
        antonyms: ['inexpressive', 'blank', 'unemotional', 'poker-faced'],
        raw_synonyms: 'evocative, eloquent, revealing, meaningful',
        raw_antonyms: 'inexpressive, blank, unemotional, poker-faced',
        sentence: 'The classical dancer\'s expressive facial gestures conveyed intricate mythological narratives without words.',
        sentence_meaning: 'ধ্রুপদী নৃত্যশিল্পীর ভাবব্যঞ্জক মুখের অভিব্যক্তি কোনো কথা ছাড়াই জটিল পৌরাণিক কাহিনি ফুটিয়ে তুলেছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 260,
        word: 'Insightful',
        ipa: '/ˈɪnsaɪtfl/',
        pos: 'adj',
        meaning: 'অন্তর্দৃষ্টিপূর্ণ, গভীর উপলব্ধিযুক্ত',
        synonyms: ['perceptive', 'discerning', 'penetrating', 'astute'],
        antonyms: ['unperceptive', 'shallow', 'obtuse', 'uninsightful'],
        raw_synonyms: 'perceptive, discerning, penetrating, astute',
        raw_antonyms: 'unperceptive, shallow, obtuse, uninsightful',
        sentence: 'Her insightful critique illuminated subtle thematic layers in the author\'s classic novel.',
        sentence_meaning: 'তাঁর অন্তর্দৃষ্টিপূর্ণ পর্যালোচনা লেখকের চিরায়ত উপন্যাসের সূক্ষ্ম বিষয়ভিত্তিক স্তরগুলোকে উন্মোচিত করেছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      }
    ]
  },
  {
    level_id: 53,
    title: 'Level 53: Vocabulary',
    unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)',
    category: 'Vocabulary',
    items: [
      {
        id: 261,
        word: 'Distinguished',
        ipa: '/dɪˈstɪŋɡwɪʃt/',
        pos: 'adj',
        meaning: 'সম্মানিত, বিশিষ্ট ও প্রখ্যাত',
        synonyms: ['eminent', 'renowned', 'esteemed', 'illustrious'],
        antonyms: ['unremarkable', 'ordinary', 'ignominious', 'obscure'],
        raw_synonyms: 'eminent, renowned, esteemed, illustrious',
        raw_antonyms: 'unremarkable, ordinary, ignominious, obscure',
        sentence: 'A distinguished panel of jurists was appointed to review the nation\'s constitutional amendments.',
        sentence_meaning: 'দেশের সাংবিধানিক সংশোধনী পর্যালোচনার জন্য বিশিষ্ট আইনবিদদের একটি প্যানেল নিযুক্ত করা হয়েছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 262,
        word: 'Bohemian',
        ipa: '/boʊˈhiːmiən/',
        pos: 'adj',
        meaning: 'প্রথামুক্ত, বাঁধনহারা বা যাযাবর স্বভাবের',
        synonyms: ['unconventional', 'nonconformist', 'artistic', 'free-spirited'],
        antonyms: ['conventional', 'traditional', 'orthodox', 'conformist'],
        raw_synonyms: 'unconventional, nonconformist, artistic, free-spirited',
        raw_antonyms: 'conventional, traditional, orthodox, conformist',
        sentence: 'The poet embraced a bohemian lifestyle, traveling across Europe with minimal possessions.',
        sentence_meaning: 'কবি একটি বাঁধনহারা প্রথামুক্ত জীবনধারা বেছে নিয়েছিলেন এবং সামান্য জিনিসপত্র নিয়ে ইউরোপজুড়ে ভ্রমণ করেছিলেন।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 263,
        word: 'Extensively',
        ipa: '/ɪkˈstensɪvli/',
        pos: 'adv',
        meaning: 'ব্যাপকভাবে, বিশদ পরিসরে',
        synonyms: ['broadly', 'comprehensively', 'widely', 'thoroughly'],
        antonyms: ['narrowly', 'scantly', 'minimally', 'partially'],
        raw_synonyms: 'broadly, comprehensively, widely, thoroughly',
        raw_antonyms: 'narrowly, scantly, minimally, partially',
        sentence: 'The researcher traveled extensively throughout Southeast Asia to collect rare botanical specimens.',
        sentence_meaning: 'বিরল উদ্ভিদের নমুনা সংগ্রহের জন্য গবেষক দক্ষিণ-পূর্ব এশিয়াজুড়ে ব্যাপকভাবে ভ্রমণ করেছিলেন।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 264,
        word: 'Vision',
        ipa: '/ˈvɪʒn/',
        pos: 'n',
        meaning: 'দূরদৃষ্টি, দূরদর্শী কল্পনা বা পরিকল্পনা',
        synonyms: ['foresight', 'perception', 'discernment', 'outlook'],
        antonyms: ['shortsightedness', 'blindness', 'myopia', 'improvidence'],
        raw_synonyms: 'foresight, perception, discernment, outlook',
        raw_antonyms: 'shortsightedness, blindness, myopia, improvidence',
        sentence: 'The founder had a transformative vision for making renewable solar energy affordable worldwide.',
        sentence_meaning: 'বিশ্বজুড়ে নবায়নযোগ্য সৌরশক্তিকে সাশ্রয়ী করে তোলার ব্যাপারে প্রতিষ্ঠাতার একটি যুগান্তকারী দূরদৃষ্টি ছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 265,
        word: 'Widespread',
        ipa: '/ˈwaɪdspred/',
        pos: 'adj',
        meaning: 'ব্যাপক, বহুদূর বিস্তৃত',
        synonyms: ['prevalent', 'extensive', 'ubiquitous', 'rampant'],
        antonyms: ['limited', 'localized', 'rare', 'restricted'],
        raw_synonyms: 'prevalent, extensive, ubiquitous, rampant',
        raw_antonyms: 'limited, localized, rare, restricted',
        sentence: 'The sudden policy announcement sparked widespread debate among economists and politicians.',
        sentence_meaning: 'হঠাৎ নীতি ঘোষণার ফলে অর্থনীতিবিদ এবং রাজনীতিবিদদের মধ্যে ব্যাপক বিতর্ক শুরু হয়।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      }
    ]
  },
  {
    level_id: 54,
    title: 'Level 54: Vocabulary',
    unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)',
    category: 'Vocabulary',
    items: [
      {
        id: 266,
        word: 'Recognition',
        ipa: '/ˌrekəɡˈnɪʃn/',
        pos: 'n',
        meaning: 'স্বীকৃতি, সম্মান ও সমাদর',
        synonyms: ['acknowledgment', 'appreciation', 'acclaim', 'honor'],
        antonyms: ['disregard', 'denial', 'anonymity', 'rejection'],
        raw_synonyms: 'acknowledgment, appreciation, acclaim, honor',
        raw_antonyms: 'disregard, denial, anonymity, rejection',
        sentence: 'After decades of dedicated service, the rural teacher finally received national recognition.',
        sentence_meaning: 'কয়েক দশকের একনিষ্ঠ সেবার পর অবশেষে গ্রামীণ শিক্ষকটি জাতীয় স্বীকৃতি লাভ করেন।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 267,
        word: 'Retrospective',
        ipa: '/ˌretrəˈspektɪv/',
        pos: 'n',
        meaning: 'শিল্পকর্মের অতীত সামগ্রিক প্রদর্শনী',
        synonyms: ['comprehensive exhibition', 'review', 'retrospect', 'survey'],
        antonyms: ['preview', 'prospective', 'forecast'],
        raw_synonyms: 'comprehensive exhibition, review, retrospect, survey',
        raw_antonyms: 'preview, prospective, forecast',
        sentence: 'The national gallery organized a grand retrospective showcasing Zainul Abedin\'s iconic life works.',
        sentence_meaning: 'জাতীয় গ্যালারি জয়নুল আবেদিনের জীবনের স্মরণীয় শিল্পকর্মগুলো প্রদর্শন করে একটি বৃহৎ অতীত সামগ্রিক প্রদর্শনীর আয়োজন করেছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 268,
        word: 'Solidify',
        ipa: '/səˈlɪdɪfaɪ/',
        pos: 'v',
        meaning: 'দৃঢ় করা, মজবুত বা সংহত করা',
        synonyms: ['strengthen', 'consolidate', 'reinforce', 'harden'],
        antonyms: ['weaken', 'dissolve', 'soften', 'undermine'],
        raw_synonyms: 'strengthen, consolidate, reinforce, harden',
        raw_antonyms: 'weaken, dissolve, soften, undermine',
        sentence: 'Signing the trade pact will solidify economic cooperation between the two regional partners.',
        sentence_meaning: 'বাণিজ্য চুক্তি স্বাক্ষর দুই আঞ্চলিক অংশীদারের মধ্যে অর্থনৈতিক সহযোগিতাকে আরও দৃঢ় করবে।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 269,
        word: 'Underprivileged',
        ipa: '/ˌʌndərˈprɪvəlɪdʒd/',
        pos: 'adj',
        meaning: 'সুবিধাবঞ্চিত, অধিকারবঞ্চিত',
        synonyms: ['disadvantaged', 'deprived', 'impoverished', 'destitute'],
        antonyms: ['privileged', 'wealthy', 'affluent', 'favored'],
        raw_synonyms: 'disadvantaged, deprived, impoverished, destitute',
        raw_antonyms: 'privileged, wealthy, affluent, favored',
        sentence: 'The charity organization provides free educational materials and nutritious meals to underprivileged children.',
        sentence_meaning: 'দাতব্য সংস্থাটি সুবিধাবঞ্চিত শিশুদের বিনামূল্যে শিক্ষাসামগ্রী ও পুষ্টিকর খাবার সরবরাহ করে।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 270,
        word: 'Sheer',
        ipa: '/ʃɪr/',
        pos: 'adj',
        meaning: 'সম্পূর্ণ, নিখাদ বা কেবল',
        synonyms: ['absolute', 'pure', 'utter', 'unmitigated'],
        antonyms: ['partial', 'qualified', 'limited', 'doubtful'],
        raw_synonyms: 'absolute, pure, utter, unmitigated',
        raw_antonyms: 'partial, qualified, limited, doubtful',
        sentence: 'Through sheer determination and perseverance, she overcame extreme adversity to succeed.',
        sentence_meaning: 'কেবলমাত্র দৃঢ় সংকল্প ও অধ্যবসায়ের মাধ্যমে তিনি চরম প্রতিকূলতা কাটিয়ে সাফল্য অর্জন করেছিলেন।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      }
    ]
  },
  {
    level_id: 55,
    title: 'Level 55: Vocabulary',
    unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)',
    category: 'Vocabulary',
    items: [
      {
        id: 271,
        word: 'Enduring',
        ipa: '/ɪnˈdʊrɪŋ/',
        pos: 'adj',
        meaning: 'চিরস্থায়ী, দীর্ঘস্থায়ী ও টেকসই',
        synonyms: ['lasting', 'perpetual', 'abiding', 'durable'],
        antonyms: ['transient', 'fleeting', 'ephemeral', 'temporary'],
        raw_synonyms: 'lasting, perpetual, abiding, durable',
        raw_antonyms: 'transient, fleeting, ephemeral, temporary',
        sentence: 'Rabindranath Tagore\'s timeless literary compositions have achieved an enduring place in global literature.',
        sentence_meaning: 'রবীন্দ্রনাথ ঠাকুরের কালজয়ী সাহিত্যকর্ম বিশ্বসাহিত্যে এক চিরস্থায়ী স্থান অধিকার করেছে।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 272,
        word: 'Afford',
        ipa: '/əˈfɔːrd/',
        pos: 'v',
        meaning: 'প্রদান করা, সুযোগ দেওয়া বা সামর্থ্য থাকা',
        synonyms: ['provide', 'supply', 'furnish', 'yield'],
        antonyms: ['deny', 'refuse', 'withhold', 'deprive'],
        raw_synonyms: 'provide, supply, furnish, yield',
        raw_antonyms: 'deny, refuse, withhold, deprive',
        sentence: 'The scholarship will afford talented rural students the opportunity to study at world-class universities.',
        sentence_meaning: 'বৃত্তিটি মেধাবী গ্রামীণ শিক্ষার্থীদের বিশ্বমানের বিশ্ববিদ্যালয়ে পড়ার সুযোগ প্রদান করবে।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 273,
        word: 'Muscular',
        ipa: '/ˈmʌskjələr/',
        pos: 'adj',
        meaning: 'পেশিবহুল, সুঠাম ও বলিষ্ঠ',
        synonyms: ['brawny', 'stout', 'athletic', 'sinewy'],
        antonyms: ['frail', 'skinny', 'puny', 'feeble'],
        raw_synonyms: 'brawny, stout, athletic, sinewy',
        raw_antonyms: 'frail, skinny, puny, feeble',
        sentence: 'The sculpture depicted a muscular warrior ready to defend his homeland against invaders.',
        sentence_meaning: 'ভাস্কর্যটিতে এক পেশিবহুল যোদ্ধাকে আক্রমণকারীদের বিরুদ্ধে মাতৃভূমি রক্ষা করার জন্য প্রস্তুত দেখাচ্ছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 274,
        word: 'Stature',
        ipa: '/ˈstætʃər/',
        pos: 'n',
        meaning: 'দৈহিক উচ্চতা, শারীরিক গঠন',
        synonyms: ['height', 'tallness', 'physique', 'build'],
        antonyms: ['shortness', 'lowness', 'diminutiveness'],
        raw_synonyms: 'height, tallness, physique, build',
        raw_antonyms: 'shortness, lowness, diminutiveness',
        sentence: 'The basketball player\'s towering stature gave him a commanding advantage under the basket.',
        sentence_meaning: 'বাস্কেটবল খেলোয়াড়টির সুবিশাল শারীরিক উচ্চতা তাকে বাস্কেটের নিচে অসাধারণ সুবিধা দিয়েছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 275,
        word: 'Legacy',
        ipa: '/ˈleɡəsi/',
        pos: 'n',
        meaning: 'উত্তরাধিকার, ঐতিহাসিক কীর্তি',
        synonyms: ['heritage', 'inheritance', 'bequest', 'patrimony'],
        antonyms: ['dispossession', 'divestment', 'renunciation'],
        raw_synonyms: 'heritage, inheritance, bequest, patrimony',
        raw_antonyms: 'dispossession, divestment, renunciation',
        sentence: 'Nelson Mandela left a legacy of resilience, reconciliation, and profound moral courage.',
        sentence_meaning: 'নেলসন ম্যান্ডেলা সহনশীলতা, পুনর্মিলন এবং গভীর নৈতিক সাহসের এক অনন্য উত্তরাধিকার রেখে গেছেন।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      }
    ]
  },
  {
    level_id: 56,
    title: 'Level 56: Vocabulary',
    unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)',
    category: 'Vocabulary',
    items: [
      {
        id: 276,
        word: 'Prestigious',
        ipa: '/preˈstɪdʒəs/',
        pos: 'adj',
        meaning: 'সম্মানজনক, মর্যাদাপূর্ণ',
        synonyms: ['renowned', 'esteemed', 'distinguished', 'reputable'],
        antonyms: ['disreputable', 'obscure', 'inglorious', 'unprestigious'],
        raw_synonyms: 'renowned, esteemed, distinguished, reputable',
        raw_antonyms: 'disreputable, obscure, inglorious, unprestigious',
        sentence: 'Graduating from such a prestigious institution opens countless lucrative career pathways.',
        sentence_meaning: 'এমন একটি মর্যাদাপূর্ণ প্রতিষ্ঠান থেকে স্নাতক সম্পন্ন করা অসংখ্য লাভজনক ক্যারিয়ারের পথ খুলে দেয়।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 277,
        word: 'Accolade',
        ipa: '/ˈækəleɪd/',
        pos: 'n',
        meaning: 'সম্মাননা, উচ্ছ্বসিত প্রশংসা',
        synonyms: ['tribute', 'commendation', 'honor', 'award'],
        antonyms: ['criticism', 'censure', 'condemnation', 'rebuke'],
        raw_synonyms: 'tribute, commendation, honor, award',
        raw_antonyms: 'criticism, censure, condemnation, rebuke',
        sentence: 'The filmmaker received the highest cinematic accolade at the Cannes Film Festival.',
        sentence_meaning: 'চলচ্চিত্র নির্মাতা কান চলচ্চিত্র উৎসবে সর্বোচ্চ চলচ্চিত্র সম্মাননা অর্জন করেছিলেন।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 278,
        word: 'Laudatory',
        ipa: '/ˈlɔːdətɔːri/',
        pos: 'adj',
        meaning: 'প্রশংসাসূচক, স্তুতিপূর্ণ',
        synonyms: ['praiseful', 'complimentary', 'eulogistic', 'acclamatory'],
        antonyms: ['derogatory', 'critical', 'disparaging', 'scathing'],
        raw_synonyms: 'praiseful, complimentary, eulogistic, acclamatory',
        raw_antonyms: 'derogatory, critical, disparaging, scathing',
        sentence: 'The newspaper published a laudatory editorial commending the emergency rescue workers.',
        sentence_meaning: 'সংবাদপত্রটি জরুরি উদ্ধারকর্মীদের প্রশংসা করে একটি প্রশংসাসূচক সম্পাদকীয় প্রকাশ করেছে।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 279,
        word: 'Acclaimed',
        ipa: '/əˈkleɪmd/',
        pos: 'adj',
        meaning: 'সর্বজনস্বীকৃত ও প্রশংসিত',
        synonyms: ['celebrated', 'lauded', 'hailed', 'distinguished'],
        antonyms: ['criticized', 'unrecognized', 'condemned', 'unappreciated'],
        raw_synonyms: 'celebrated, lauded, hailed, distinguished',
        raw_antonyms: 'criticized, unrecognized, condemned, unappreciated',
        sentence: 'She is an internationally acclaimed author whose books have been translated into thirty languages.',
        sentence_meaning: 'তিনি একজন আন্তর্জাতিকভাবে প্রশংসিত লেখক যাঁর বই ত্রিশটি ভাষায় অনূদিত হয়েছে।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 280,
        word: 'Exaggerated',
        ipa: '/ɪɡˈzædʒəreɪtɪd/',
        pos: 'adj',
        meaning: 'অতিরঞ্জিত, অতিরিক্ত করে বলা',
        synonyms: ['overstated', 'hyperbolic', 'magnified', 'amplified'],
        antonyms: ['understated', 'accurate', 'unexaggerated', 'realistic'],
        raw_synonyms: 'overstated, hyperbolic, magnified, amplified',
        raw_antonyms: 'understated, accurate, unexaggerated, realistic',
        sentence: 'Rumors about the imminent financial collapse of the bank proved to be wildly exaggerated.',
        sentence_meaning: 'ব্যাংকের আসন্ন আর্থিক পতনের গুজবটি ব্যাপকভাবে অতিরঞ্জিত প্রমাণিত হয়েছিল।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      }
    ]
  },
  {
    level_id: 57,
    title: 'Level 57: Vocabulary',
    unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)',
    category: 'Vocabulary',
    items: [
      {
        id: 281,
        word: 'Pioneer',
        ipa: '/ˌpaɪəˈnɪr/',
        pos: 'n',
        meaning: 'অগ্রদূত, পথপ্রদর্শক',
        synonyms: ['trailblazer', 'pathfinder', 'innovator', 'forerunner'],
        antonyms: ['follower', 'imitator', 'disciple', 'traditionalist'],
        raw_synonyms: 'trailblazer, pathfinder, innovator, forerunner',
        raw_antonyms: 'follower, imitator, disciple, traditionalist',
        sentence: 'Marie Curie was a fearless pioneer in the field of radioactivity and nuclear chemistry.',
        sentence_meaning: 'মেরি কুরি তেজস্ক্রিয়তা ও পারমাণবিক রসায়ন ক্ষেত্রে একজন নির্ভীক অগ্রদূত ছিলেন।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 282,
        word: 'Proclaim',
        ipa: '/prəˈkleɪm/',
        pos: 'v',
        meaning: 'আনুষ্ঠানিকভাবে ঘোষণা করা, জারি করা',
        synonyms: ['declare', 'announce', 'herald', 'broadcast'],
        antonyms: ['conceal', 'suppress', 'withhold', 'deny'],
        raw_synonyms: 'declare, announce, herald, broadcast',
        raw_antonyms: 'conceal, suppress, withhold, deny',
        sentence: 'The president stepped up to the podium to proclaim a national holiday celebrating unity.',
        sentence_meaning: 'রাষ্ট্রপতি ঐক্য উদযাপনের জন্য একটি জাতীয় ছুটি ঘোষণা করতে মঞ্চে উঠলেন।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 283,
        word: 'Aptly',
        ipa: '/ˈæptli/',
        pos: 'adv',
        meaning: 'যথাযথভাবে, মানানসইভাবে',
        synonyms: ['suitably', 'appropriately', 'fittingly', 'befittingly'],
        antonyms: ['inappropriately', 'unsuitably', 'improperly', 'inaptly'],
        raw_synonyms: 'suitably, appropriately, fittingly, befittingly',
        raw_antonyms: 'inappropriately, unsuitably, improperly, inaptly',
        sentence: 'The resort is aptly named "Paradise Cove" because of its crystal-clear waters and golden sands.',
        sentence_meaning: 'স্বচ্ছ জলরাশি ও সোনালি বালির কারণে রিসোর্টটির নাম যথাযথভাবেই "প্যারাডাইস কোভ" রাখা হয়েছে।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 284,
        word: 'Progressive',
        ipa: '/prəˈɡresɪv/',
        pos: 'adj',
        meaning: 'প্রগতিশীল, সংস্কারকামী',
        synonyms: ['forward-thinking', 'innovative', 'modern', 'reformist'],
        antonyms: ['reactionary', 'conservative', 'traditional', 'regressive'],
        raw_synonyms: 'forward-thinking, innovative, modern, reformist',
        raw_antonyms: 'reactionary, conservative, traditional, regressive',
        sentence: 'The institution adopted progressive policies designed to promote inclusivity and equity.',
        sentence_meaning: 'প্রতিষ্ঠানটি অন্তর্ভুক্তি এবং সমতা বৃদ্ধি করার লক্ষ্যে প্রগতিশীল নীতি গ্রহণ করেছে।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 285,
        word: 'Fascinate',
        ipa: '/ˈfæsɪneɪt/',
        pos: 'v',
        meaning: 'মুগ্ধ করা, তীব্রভাবে আকৃষ্ট করা',
        synonyms: ['captivate', 'enchant', 'charm', 'allure'],
        antonyms: ['repel', 'bore', 'disgust', 'disenchant'],
        raw_synonyms: 'captivate, enchant, charm, allure',
        raw_antonyms: 'repel, bore, disgust, disenchant',
        sentence: 'Mysteries of outer space and astronomy never fail to fascinate young curious minds.',
        sentence_meaning: 'মহাকাশ ও জ্যোতির্বিজ্ঞানের রহস্য সবসময়ই তরুণ কৌতূহলী মনকে মুগ্ধ করতে ব্যর্থ হয় না।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      }
    ]
  },
  {
    level_id: 58,
    title: 'Level 58: Vocabulary',
    unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)',
    category: 'Vocabulary',
    items: [
      {
        id: 286,
        word: 'Artefact',
        ipa: '/ˈɑːrtɪfækt/',
        pos: 'n',
        meaning: 'ঐতিহাসিক হস্তশিল্প বা প্রত্নবস্তু',
        synonyms: ['relic', 'antique', 'handicraft', 'curio'],
        antonyms: ['natural specimen', 'modern creation'],
        raw_synonyms: 'relic, antique, handicraft, curio',
        raw_antonyms: 'natural specimen, modern creation',
        sentence: 'Archaeologists discovered an ancient terracotta artefact dating back to the third century BCE.',
        sentence_meaning: 'প্রত্নতাত্ত্বিকরা খ্রিস্টপূর্ব তৃতীয় শতকের একটি প্রাচীন পোড়ামাটির প্রত্নবস্তু আবিষ্কার করেছেন।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 287,
        word: 'Motif',
        ipa: '/moʊˈtiːf/',
        pos: 'n',
        meaning: 'শিল্পকর্মের মূল নকশা বা মূল ভাব',
        synonyms: ['theme', 'pattern', 'concept', 'design element'],
        antonyms: ['deviation', 'aberration', 'discordance'],
        raw_synonyms: 'theme, pattern, concept, design element',
        raw_antonyms: 'deviation, aberration, discordance',
        sentence: 'A recurring floral motif was embroidered skillfully along the borders of the silk sari.',
        sentence_meaning: 'রেশমি শাড়ির পাড়ে একটি পুনরাবৃত্তিমূলক ফুলের নকশা দক্ষতার সাথে সূচিকর্ম করা হয়েছিল।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 288,
        word: 'Depict',
        ipa: '/dɪˈpɪkt/',
        pos: 'v',
        meaning: 'চিত্রিত করা, ফুটিয়ে তোলা বা বর্ণনা করা',
        synonyms: ['portray', 'illustrate', 'render', 'represent'],
        antonyms: ['falsify', 'distort', 'obscure', 'misrepresent'],
        raw_synonyms: 'portray, illustrate, render, represent',
        raw_antonyms: 'falsify, distort, obscure, misrepresent',
        sentence: 'The oil painting depicts rural farmers harvesting golden paddy during autumn.',
        sentence_meaning: 'তেলচিত্রটিতে শরতের সময় গ্রামীণ কৃষকদের সোনালি ধান কাটার দৃশ্য চিত্রিত করা হয়েছে।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 289,
        word: 'Inaugurate',
        ipa: '/ɪˈnɔːɡjəreɪt/',
        pos: 'v',
        meaning: 'উদ্বোধন করা, আনুষ্ঠানিকভাবে শুরু করা',
        synonyms: ['launch', 'commence', 'instigate', 'initiate'],
        antonyms: ['terminate', 'close', 'conclude', 'abolish'],
        raw_synonyms: 'launch, commence, instigate, initiate',
        raw_antonyms: 'terminate, close, conclude, abolish',
        sentence: 'The Prime Minister arrived on schedule to inaugurate the newly built four-lane bridge.',
        sentence_meaning: 'নতুন নির্মিত চার লেনের সেতুটি উদ্বোধন করতে প্রধানমন্ত্রী নির্ধারিত সময়ে উপস্থিত হয়েছিলেন।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 290,
        word: 'Remains',
        ipa: '/rɪˈmeɪnz/',
        pos: 'n',
        meaning: 'ধ্বংসাবশেষ, অবশিষ্টাংশ',
        synonyms: ['ruins', 'relics', 'remnants', 'vestiges'],
        antonyms: ['whole', 'entirety', 'structure', 'aggregate'],
        raw_synonyms: 'ruins, relics, remnants, vestiges',
        raw_antonyms: 'whole, entirety, structure, aggregate',
        sentence: 'Visitors flocked to examine the excavated archaeological remains of the ancient city.',
        sentence_meaning: 'প্রাচীন শহরের খননকৃত প্রত্নতাত্ত্বিক ধ্বংসাবশেষ দেখতে দর্শনার্থীরা ভিড় জমিয়েছিলেন।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      }
    ]
  },
  {
    level_id: 59,
    title: 'Level 59: Vocabulary',
    unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)',
    category: 'Vocabulary',
    items: [
      {
        id: 291,
        word: 'Intuitive',
        ipa: '/ɪnˈtuːɪtɪv/',
        pos: 'adj',
        meaning: 'সহজাত, স্বজ্ঞাত ও সহজবোধ্য',
        synonyms: ['instinctive', 'spontaneous', 'innate', 'perceptive'],
        antonyms: ['deliberate', 'calculated', 'reasoned', 'learned'],
        raw_synonyms: 'instinctive, spontaneous, innate, perceptive',
        raw_antonyms: 'deliberate, calculated, reasoned, learned',
        sentence: 'The smartphone software boasts an intuitive interface that even toddlers can navigate easily.',
        sentence_meaning: 'স্মার্টফোনের সফটওয়্যারটিতে একটি সহজবোধ্য ইন্টারফেস রয়েছে যা ছোট শিশুরাও সহজে পরিচালনা করতে পারে।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 292,
        word: 'Stature',
        ipa: '/ˈstætʃər/',
        pos: 'n',
        meaning: 'সামাজিক মর্যাদা, সম্মানজনক অবস্থান',
        synonyms: ['prestige', 'standing', 'reputation', 'eminence'],
        antonyms: ['insignificance', 'obscurity', 'disrepute', 'unimportance'],
        raw_synonyms: 'prestige, standing, reputation, eminence',
        raw_antonyms: 'insignificance, obscurity, disrepute, unimportance',
        sentence: 'As an internationally acclaimed jurist, her moral stature remains beyond dispute.',
        sentence_meaning: 'একজন আন্তর্জাতিক খ্যাতিসম্পন্ন আইনবিদ হিসেবে তাঁর নৈতিক মর্যাদা প্রশ্নাতীত।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 293,
        word: 'Anonymous',
        ipa: '/əˈnɑːnɪməs/',
        pos: 'adj',
        meaning: 'নামবিহীন, অজ্ঞাতপরিচয়',
        synonyms: ['unnamed', 'incognito', 'unidentified', 'nameless'],
        antonyms: ['identified', 'named', 'known', 'celebrated'],
        raw_synonyms: 'unnamed, incognito, unidentified, nameless',
        raw_antonyms: 'identified, named, known, celebrated',
        sentence: 'An anonymous philanthropist funded the entire scholarship program for underprivileged students.',
        sentence_meaning: 'একজন অজ্ঞাতপরিচয় দানবীর সুবিধাবঞ্চিত শিক্ষার্থীদের জন্য পুরো বৃত্তি কর্মসূচিতে অর্থায়ন করেছেন।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 294,
        word: 'Tactile',
        ipa: '/ˈtæktaɪl/',
        pos: 'adj',
        meaning: 'স্পর্শসম্বন্ধীয়, স্পর্শযোগ্য',
        synonyms: ['tangible', 'palpable', 'touchable', 'physical'],
        antonyms: ['intangible', 'imperceptible', 'incorporeal', 'abstract'],
        raw_synonyms: 'tangible, palpable, touchable, physical',
        raw_antonyms: 'intangible, imperceptible, incorporeal, abstract',
        sentence: 'Braille writing allows visually impaired individuals to read through tactile sensory perception.',
        sentence_meaning: 'ব্রেইল লিখনপদ্ধতি দৃষ্টিপ্রতিবন্ধী ব্যক্তিদের স্পর্শানুভূতির মাধ্যমে পড়ার সুযোগ করে দেয়।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 295,
        word: 'Generate',
        ipa: '/ˈdʒenəreɪt/',
        pos: 'v',
        meaning: 'উৎপন্ন করা, তৈরি বা সৃষ্টি করা',
        synonyms: ['produce', 'create', 'yield', 'engender'],
        antonyms: ['destroy', 'extinguish', 'annihilate', 'dismantle'],
        raw_synonyms: 'produce, create, yield, engender',
        raw_antonyms: 'destroy, extinguish, annihilate, dismantle',
        sentence: 'The newly installed solar farm has the capacity to generate clean electricity for the entire town.',
        sentence_meaning: 'নতুন স্থাপিত সৌর বিদ্যুৎ খামারটির পুরো শহরের জন্য পরিচ্ছন্ন বিদ্যুৎ উৎপাদন করার ক্ষমতা রয়েছে।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      }
    ]
  },
  {
    level_id: 60,
    title: 'Level 60: Vocabulary',
    unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)',
    category: 'Vocabulary',
    items: [
      {
        id: 296,
        word: 'Animate',
        ipa: '/ˈænɪmeɪt/',
        pos: 'v',
        meaning: 'প্রাণবন্ত করা, উদ্দীপ্ত করা',
        synonyms: ['enliven', 'energize', 'invigorate', 'stimulate'],
        antonyms: ['deaden', 'depress', 'dull', 'subdue'],
        raw_synonyms: 'enliven, energize, invigorate, stimulate',
        raw_antonyms: 'deaden, depress, dull, subdue',
        sentence: 'The energetic speaker knew exactly how to animate the tired audience with vivid stories.',
        sentence_meaning: 'প্রাণবন্ত বক্তা ঠিক জানতেন কীভাবে প্রাণবন্ত গল্পের মাধ্যমে ক্লান্ত শ্রোতাদের উদ্দীপ্ত করতে হয়।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 297,
        word: 'Dynamic',
        ipa: '/daɪˈnæmɪk/',
        pos: 'adj',
        meaning: 'গতিশীল, উদ্যমী ও পরিবর্তনশীল',
        synonyms: ['energetic', 'progressive', 'vibrant', 'vigorous'],
        antonyms: ['static', 'idle', 'sluggish', 'inactive'],
        raw_synonyms: 'energetic, progressive, vibrant, vigorous',
        raw_antonyms: 'static, idle, sluggish, inactive',
        sentence: 'A dynamic global market requires companies to innovate and adapt rapidly to new technologies.',
        sentence_meaning: 'একটি গতিশীল বৈশ্বিক বাজারের জন্য কোম্পানিগুলোকে দ্রুত নতুন প্রযুক্তির সাথে খাপ খাইয়ে নিতে এবং উদ্ভাবন করতে হয়।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 298,
        word: 'Evolve',
        ipa: '/ɪˈvɑːlv/',
        pos: 'v',
        meaning: 'ক্রমবিকাশ লাভ করা, ধীরে ধীরে বিকশিত হওয়া',
        synonyms: ['develop', 'mature', 'progress', 'advance'],
        antonyms: ['deteriorate', 'regress', 'devolve', 'stagnate'],
        raw_synonyms: 'develop, mature, progress, advance',
        raw_antonyms: 'deteriorate, regress, devolve, stagnate',
        sentence: 'Living organisms evolve over millions of years to adapt to changing environments.',
        sentence_meaning: 'পরিবর্তনশীল পরিবেশের সাথে খাপ খাইয়ে নিতে জীবজগৎ লক্ষ লক্ষ বছর ধরে ক্রমবিকাশ লাভ করে।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 299,
        word: 'Abreast',
        ipa: '/əˈbrest/',
        pos: 'adv',
        meaning: 'পাশাপাশি, সমতালে বা হালনাগাদ তথ্যে',
        synonyms: ['alongside', 'side by side', 'in step', 'aligned'],
        antonyms: ['behind', 'out of step', 'trailing', 'apart'],
        raw_synonyms: 'alongside, side by side, in step, aligned',
        raw_antonyms: 'behind, out of step, trailing, apart',
        sentence: 'Professionals must read scientific journals continuously to keep abreast of modern medical advances.',
        sentence_meaning: 'আধুনিক চিকিৎসার অগ্রগতির সাথে সমতালে থাকতে পেশাজীবীদের নিয়মিত বৈজ্ঞানিক জার্নাল পড়তে হবে।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      },
      {
        id: 300,
        word: 'Ancient',
        ipa: '/ˈeɪnʃənt/',
        pos: 'adj',
        meaning: 'প্রাচীন, বহু পুরোনো',
        synonyms: ['archaic', 'primitive', 'antique', 'primordial'],
        antonyms: ['modern', 'contemporary', 'recent', 'novel'],
        raw_synonyms: 'archaic, primitive, antique, primordial',
        raw_antonyms: 'modern, contemporary, recent, novel',
        sentence: 'The Great Pyramids of Giza stand as a timeless wonder of ancient engineering.',
        sentence_meaning: 'গিজার মহাপ্রাসাদগুলো বা পিরামিড প্রাচীন প্রকৌশলবিদ্যার এক কালজয়ী বিস্ময় হিসেবে দাঁড়িয়ে আছে।',
        category: 'Vocabulary',
        unit: 'Image 10 (image (10).jpg) - Vocabulary (Unit:2 continued)'
      }
    ]
  }
];

const outDir = path.join(__dirname, '..', 'public', 'data', 'levels');
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

levelsData.forEach(lvl => {
  const filePath = path.join(outDir, `level_${lvl.level_id}.json`);
  fs.writeFileSync(filePath, JSON.stringify(lvl, null, 2) + '\n', 'utf8');
  console.log(`Saved ${filePath}`);
});

console.log('All level files generated successfully.');
