const fs = require('fs');
const path = require('path');

const levels = [
  {
    level_id: 111,
    title: 'Level 111: Phrasal Verb',
    unit: 'Image 19 (image (19).jpg) - Phrasal Verbs',
    category: 'Phrasal Verb',
    items: [
      {
        id: 551,
        word: 'Come off',
        ipa: '/kʌm ɒf/',
        pos: 'phrase',
        meaning: 'সম্পন্ন হওয়া, সফলভাবে ঘটা',
        synonyms: ['take place', 'succeed', 'occur', 'transpire'],
        antonyms: ['fail', 'fall through', 'collapse', 'misfire'],
        raw_synonyms: 'take place, succeed, occur, transpire',
        raw_antonyms: 'fail, fall through, collapse, misfire',
        sentence: 'The annual sports competition came off successfully despite the morning rain.',
        sentence_meaning: 'সকালের বৃষ্টি সত্ত্বেও বার্ষিক ক্রীড়া প্রতিযোগিতা সফলভাবে সম্পন্ন হয়েছিল।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 552,
        word: 'Come out',
        ipa: '/kʌm aʊt/',
        pos: 'phrase',
        meaning: 'প্রকাশিত হওয়া, জনসমক্ষে আসা',
        synonyms: ['be published', 'emerge', 'be revealed', 'appear'],
        antonyms: ['remain hidden', 'disappear', 'vanish', 'be concealed'],
        raw_synonyms: 'be published, emerge, be revealed, appear',
        raw_antonyms: 'remain hidden, disappear, vanish, be concealed',
        sentence: 'The board exam results will come out on the official website next Monday.',
        sentence_meaning: 'বোর্ড পরীক্ষার ফলাফল আগামী সোমবার অফিসিয়াল ওয়েবসাইটে প্রকাশিত হবে।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 553,
        word: 'Come up with',
        ipa: '/kʌm ʌp wɪð/',
        pos: 'phrase',
        meaning: 'বুদ্ধি বা পরিকল্পনা উদ্ভাবন করা, সমাধান বের করা',
        synonyms: ['devise', 'produce', 'invent', 'conceive'],
        antonyms: ['ignore', 'disregard', 'forget', 'abandon'],
        raw_synonyms: 'devise, produce, invent, conceive',
        raw_antonyms: 'ignore, disregard, forget, abandon',
        sentence: 'The brilliant engineer came up with an innovative solution to reduce energy consumption.',
        sentence_meaning: 'মেধাবী প্রকৌশলী শক্তি খরচ কমানোর জন্য একটি উদ্ভাবনী সমাধান বের করেছিলেন।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 554,
        word: 'Count on',
        ipa: '/kaʊnt ɒn/',
        pos: 'phrase',
        meaning: 'ভরসা করা, কারো ওপর নির্ভর করা',
        synonyms: ['rely on', 'depend on', 'bank on', 'trust'],
        antonyms: ['distrust', 'doubt', 'disbelieve', 'suspect'],
        raw_synonyms: 'rely on, depend on, bank on, trust',
        raw_antonyms: 'distrust, doubt, disbelieve, suspect',
        sentence: 'You can always count on your true friends during difficult times.',
        sentence_meaning: 'কঠিন সময়ে আপনি সর্বদা আপনার প্রকৃত বন্ধুদের উপর ভরসা করতে পারেন।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 555,
        word: 'Come down with',
        ipa: '/kʌm daʊn wɪð/',
        pos: 'phrase',
        meaning: 'রোগে আক্রান্ত হওয়া, অসুস্থ হয়ে পড়া',
        synonyms: ['contract', 'catch', 'fall ill with', 'develop'],
        antonyms: ['recover from', 'overcome', 'resist', 'heal'],
        raw_synonyms: 'contract, catch, fall ill with, develop',
        raw_antonyms: 'recover from, overcome, resist, heal',
        sentence: 'Several students in our class came down with a viral fever this week.',
        sentence_meaning: 'আমাদের ক্লাসের বেশ কয়েকজন শিক্ষার্থী এই সপ্তাহে ভাইরাল জ্বরে আক্রান্ত হয়েছে।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      }
    ]
  },
  {
    level_id: 112,
    title: 'Level 112: Phrasal Verb',
    unit: 'Image 19 (image (19).jpg) - Phrasal Verbs',
    category: 'Phrasal Verb',
    items: [
      {
        id: 556,
        word: 'Come round',
        ipa: '/kʌm raʊnd/',
        pos: 'phrase',
        meaning: 'সুস্থ হওয়া, আরোগ্য লাভ করা, জ্ঞান ফিরে পাওয়া',
        synonyms: ['recover', 'recuperate', 'regain consciousness', 'convalesce'],
        antonyms: ['deteriorate', 'worsen', 'faint', 'decline'],
        raw_synonyms: 'recover, recuperate, regain consciousness, convalesce',
        raw_antonyms: 'deteriorate, worsen, faint, decline',
        sentence: 'After receiving intensive medical care, the critical patient began to come round.',
        sentence_meaning: 'নিবিড় চিকিৎসা সেবা পাওয়ার পর সংকটাপন্ন রোগীটি সুস্থ হয়ে উঠতে শুরু করেন।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 557,
        word: 'Come up to',
        ipa: '/kʌm ʌp tuː/',
        pos: 'phrase',
        meaning: 'প্রত্যাশা বা মান পূরণ করা, সমান হওয়া',
        synonyms: ['match', 'equal', 'reach', 'live up to'],
        antonyms: ['fall short of', 'fail', 'disappoint', 'lag behind'],
        raw_synonyms: 'match, equal, reach, live up to',
        raw_antonyms: 'fall short of, fail, disappoint, lag behind',
        sentence: 'The new smartphone model failed to come up to the high expectations of tech enthusiasts.',
        sentence_meaning: 'নতুন স্মার্টফোন মডেলটি প্রযুক্তিপ্রেমীদের উচ্চ প্রত্যাশা পূরণ করতে ব্যর্থ হয়েছে।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 558,
        word: 'Come along',
        ipa: '/kʌm əˈlɒŋ/',
        pos: 'phrase',
        meaning: 'দ্রুত এগিয়ে আসা, তাড়া করা, উন্নতি করা',
        synonyms: ['hurry up', 'progress', 'advance', 'develop'],
        antonyms: ['lag behind', 'delay', 'stagnate', 'regress'],
        raw_synonyms: 'hurry up, progress, advance, develop',
        raw_antonyms: 'lag behind, delay, stagnate, regress',
        sentence: 'Come along, or we will miss the departure of the morning train!',
        sentence_meaning: 'তাড়াতাড়ি করো, নয়তো আমরা সকালের ট্রেনটি মিস করব!',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 559,
        word: 'Come after',
        ipa: '/kʌm ˈɑːftər/',
        pos: 'phrase',
        meaning: 'পেছনে ধাওয়া করা, অনুসরণ করা',
        synonyms: ['pursue', 'follow', 'chase', 'hunt'],
        antonyms: ['precede', 'lead', 'flee', 'retreat'],
        raw_synonyms: 'pursue, follow, chase, hunt',
        raw_antonyms: 'precede, lead, flee, retreat',
        sentence: 'The brave police officers came after the fleeing bank robbers through the crowded streets.',
        sentence_meaning: 'সাহসী পুলিশ কর্মকর্তারা জনাকীর্ণ রাস্তায় পলাতক ব্যাংক ডাকাতদের পেছনে ধাওয়া করেছিলেন।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 560,
        word: 'Cry down',
        ipa: '/kraɪ daʊn/',
        pos: 'phrase',
        meaning: 'কাউকে বা কিছুকে খাটো করা, নিন্দা করা',
        synonyms: ['belittle', 'disparage', 'decry', 'deprecate'],
        antonyms: ['praise', 'extol', 'laud', 'commend'],
        raw_synonyms: 'belittle, disparage, decry, deprecate',
        raw_antonyms: 'praise, extol, laud, commend',
        sentence: 'A wise leader should never cry down the genuine efforts of team members.',
        sentence_meaning: 'একজন বিজ্ঞ নেতার কখনই দলের সদস্যদের আন্তরিক প্রচেষ্টাকে খাটো করা উচিত নয়।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      }
    ]
  },
  {
    level_id: 113,
    title: 'Level 113: Phrasal Verb',
    unit: 'Image 19 (image (19).jpg) - Phrasal Verbs',
    category: 'Phrasal Verb',
    items: [
      {
        id: 561,
        word: 'Cry out',
        ipa: '/kraɪ aʊt/',
        pos: 'phrase',
        meaning: 'যন্ত্রণায় বা ভয়ে চিৎকার করা, তীব্র প্রতিবাদ জানানো',
        synonyms: ['shout', 'scream', 'exclaim', 'yell'],
        antonyms: ['whisper', 'remain silent', 'mutter', 'hush'],
        raw_synonyms: 'shout, scream, exclaim, yell',
        raw_antonyms: 'whisper, remain silent, mutter, hush',
        sentence: 'The injured hiker cried out for immediate help when he slipped down the rocky slope.',
        sentence_meaning: 'আহত পর্বতারোহী যখন পাথুরে ঢাল বেয়ে পিছলে পড়ে যান, তখন তিনি অবিলম্বে সাহায্যের জন্য চিৎকার করেছিলেন।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 562,
        word: 'Come down',
        ipa: '/kʌm daʊn/',
        pos: 'phrase',
        meaning: 'অর্থ পরিশোধ করা, বকেয়া মেটানো, হ্রাস পাওয়া',
        synonyms: ['pay up', 'settle', 'disburse', 'decrease'],
        antonyms: ['withhold', 'increase', 'rise', 'refuse payment'],
        raw_synonyms: 'pay up, settle, disburse, decrease',
        raw_antonyms: 'withhold, increase, rise, refuse payment',
        sentence: 'The tenant finally agreed to come down with all the overdue rent payments.',
        sentence_meaning: 'ভাড়াটিয়া অবশেষে সমস্ত বকেয়া বাড়ি ভাড়া পরিশোধ করতে সম্মত হলেন।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 563,
        word: 'Cut down',
        ipa: '/kʌt daʊn/',
        pos: 'phrase',
        meaning: 'গাছ বা কোনো কিছু কেটে মাটিতে ফেলা',
        synonyms: ['fell', 'chop down', 'hew', 'level'],
        antonyms: ['plant', 'grow', 'raise', 'cultivate'],
        raw_synonyms: 'fell, chop down, hew, level',
        raw_antonyms: 'plant, grow, raise, cultivate',
        sentence: 'Environmentalists urged the community not to cut down ancient trees in the park.',
        sentence_meaning: 'পরিবেশবাদীরা পার্কের প্রাচীন গাছগুলো কেটে না ফেলার জন্য সম্প্রদায়ের প্রতি আহ্বান জানিয়েছেন।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 564,
        word: 'Cut down',
        ipa: '/kʌt daʊn/',
        pos: 'phrase',
        meaning: 'খরচ বা পরিমাণ কমানো, হ্রাস করা',
        synonyms: ['reduce', 'curtail', 'decrease', 'slash'],
        antonyms: ['expand', 'increase', 'augment', 'boost'],
        raw_synonyms: 'reduce, curtail, decrease, slash',
        raw_antonyms: 'expand, increase, augment, boost',
        sentence: 'The company had to cut down unnecessary operational expenses to maintain profitability.',
        sentence_meaning: 'মুনাফা বজায় রাখতে কোম্পানিটিকে অপ্রয়োজনীয় পরিচালন ব্যয় কমাতে হয়েছিল।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 565,
        word: 'Cut off',
        ipa: '/kʌt ɒf/',
        pos: 'phrase',
        meaning: 'সংযোগ বিচ্ছিন্ন করা, আলাদা করা',
        synonyms: ['disconnect', 'sever', 'isolate', 'interrupt'],
        antonyms: ['connect', 'join', 'link', 'attach'],
        raw_synonyms: 'disconnect, sever, isolate, interrupt',
        raw_antonyms: 'connect, join, link, attach',
        sentence: 'The heavy blizzard cut off electrical power to several remote mountain villages.',
        sentence_meaning: 'প্রচণ্ড তুষারঝড়ে কয়েকটি দুর্গম পাহাড়ি গ্রামের বিদ্যুৎ সংযোগ বিচ্ছিন্ন হয়ে গেছে।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      }
    ]
  },
  {
    level_id: 114,
    title: 'Level 114: Phrasal Verb',
    unit: 'Image 19 (image (19).jpg) - Phrasal Verbs',
    category: 'Phrasal Verb',
    items: [
      {
        id: 566,
        word: 'Cut off',
        ipa: '/kʌt ɒf/',
        pos: 'phrase',
        meaning: 'অকালে মৃত্যুবরণ করা, জীবনাবসান ঘটা',
        synonyms: ['pass away', 'perish', 'expire', 'succumb'],
        antonyms: ['survive', 'endure', 'live long', 'thrive'],
        raw_synonyms: 'pass away, perish, expire, succumb',
        raw_antonyms: 'survive, endure, live long, thrive',
        sentence: 'The brilliant young poet was tragically cut off in the prime of his youth.',
        sentence_meaning: 'মেধাবী তরুণ কবি তাঁর যৌবনের সোনালী সময়ে মর্মান্তিকভাবে অকালে মৃত্যুবরণ করেছিলেন।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 567,
        word: 'Cut out',
        ipa: '/kʌt aʊt/',
        pos: 'phrase',
        meaning: 'ছেঁটে ফেলা, কেটে বাদ দেওয়া',
        synonyms: ['remove', 'excise', 'trim', 'snip'],
        antonyms: ['insert', 'add', 'include', 'retain'],
        raw_synonyms: 'remove, excise, trim, snip',
        raw_antonyms: 'insert, add, include, retain',
        sentence: 'The film director had to cut out several unnecessary scenes to shorten the movie.',
        sentence_meaning: 'সিনেমাটি সংক্ষিপ্ত করতে চলচ্চিত্র পরিচালককে বেশ কয়েকটি অপ্রয়োজনীয় দৃশ্য কেটে বাদ দিতে হয়েছিল।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 568,
        word: 'Cut out',
        ipa: '/kʌt aʊt/',
        pos: 'phrase',
        meaning: 'প্রতিদ্বন্দ্বীকে পরাজিত করা, ছাড়িয়ে যাওয়া',
        synonyms: ['defeat', 'outdo', 'supplant', 'outshine'],
        antonyms: ['lose to', 'surrender', 'yield', 'succumb'],
        raw_synonyms: 'defeat, outdo, supplant, outshine',
        raw_antonyms: 'lose to, surrender, yield, succumb',
        sentence: 'Through sheer perseverance, the young athlete managed to cut out his fierce rivals in the championship.',
        sentence_meaning: 'একনিষ্ঠ অধ্যবসায়ের মাধ্যমে তরুণ ক্রীড়াবিদ চ্যাম্পিয়নশিপে তার প্রবল প্রতিদ্বন্দ্বীদের পরাজিত করতে সক্ষম হয়েছিলেন।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 569,
        word: 'Cut into',
        ipa: '/kʌt ˈɪntuː/',
        pos: 'phrase',
        meaning: 'টুকরো টুকরো করে কাটা, খণ্ডন করা',
        synonyms: ['slice', 'divide', 'carve', 'chop'],
        antonyms: ['mend', 'unite', 'assemble', 'join'],
        raw_synonyms: 'slice, divide, carve, chop',
        raw_antonyms: 'mend, unite, assemble, join',
        sentence: 'She used a sharp kitchen knife to cut the ripe mango into small juicy pieces.',
        sentence_meaning: 'তিনি একটি ধারালো রান্নাঘরের ছুরি ব্যবহার করে পাকা আমটিকে ছোট ছোট রসালো টুকরো করে কেটেছিলেন।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 570,
        word: 'Cut up',
        ipa: '/kʌt ʌp/',
        pos: 'phrase',
        meaning: 'মানসিকভাবে গভীরভাবে মর্মাহত বা ব্যথিত হওয়া',
        synonyms: ['distressed', 'upset', 'heartbroken', 'grieved'],
        antonyms: ['comforted', 'cheerful', 'delighted', 'composed'],
        raw_synonyms: 'distressed, upset, heartbroken, grieved',
        raw_antonyms: 'comforted, cheerful, delighted, composed',
        sentence: 'The entire team was deeply cut up by the sudden loss of their beloved captain.',
        sentence_meaning: 'তাদের প্রিয় অধিনায়কের আকস্মিক প্রয়াণে পুরো দলটি মানসিকভাবে গভীরভাবে মর্মাহত হয়েছিল।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      }
    ]
  },
  {
    level_id: 115,
    title: 'Level 115: Phrasal Verb',
    unit: 'Image 19 (image (19).jpg) - Phrasal Verbs',
    category: 'Phrasal Verb',
    items: [
      {
        id: 571,
        word: 'Clog up',
        ipa: '/klɒɡ ʌp/',
        pos: 'phrase',
        meaning: 'আটকে যাওয়া, পথ বা নালী রুদ্ধ করা',
        synonyms: ['block', 'choke', 'obstruct', 'congest'],
        antonyms: ['unblock', 'clear', 'open', 'unclog'],
        raw_synonyms: 'block, choke, obstruct, congest',
        raw_antonyms: 'unblock, clear, open, unclog',
        sentence: 'Accumulated autumn leaves can clog up the drainage pipes during heavy rain.',
        sentence_meaning: 'ভারী বৃষ্টির সময় জমে থাকা শরতের পাতা ড্রেনেজ পাইপ আটকে দিতে পারে।',
        category: 'Phrasal Verb',
        unit: 'Image 19 (image (19).jpg) - Phrasal Verbs'
      },
      {
        id: 572,
        word: 'Call at',
        ipa: '/kɔːl æt/',
        pos: 'phrase',
        meaning: 'স্বল্প সময়ের জন্য কোথাও পরিদর্শন করা বা থামা',
        synonyms: ['visit', 'stop by', 'drop in at', 'call on'],
        antonyms: ['avoid', 'depart', 'leave', 'bypass'],
        raw_synonyms: 'visit, stop by, drop in at, call on',
        raw_antonyms: 'avoid, depart, leave, bypass',
        sentence: 'The passenger vessel will call at several major coastal ports during the cruise.',
        sentence_meaning: 'যাত্রীবাহী জাহাজটি ক্রুজ চলাকালীন বেশ কয়েকটি প্রধান উপকূলীয় বন্দরে অল্প সময়ের জন্য থামবে।',
        category: 'Phrasal Verb',
        unit: 'Image 20 (image (20).jpg) - Phrasal Verbs (Continued)'
      },
      {
        id: 573,
        word: 'Carry through',
        ipa: '/ˈkæri θruː/',
        pos: 'phrase',
        meaning: 'কোনো কাজ সফলভাবে সম্পন্ন করা, বিপদে টিকিয়ে রাখা',
        synonyms: ['accomplish', 'fulfill', 'sustain', 'complete'],
        antonyms: ['abandon', 'fail', 'neglect', 'give up'],
        raw_synonyms: 'accomplish, fulfill, sustain, complete',
        raw_antonyms: 'abandon, fail, neglect, give up',
        sentence: 'Unwavering determination and courage carried the soldiers through the brutal winter campaign.',
        sentence_meaning: 'দৃঢ় সংকল্প এবং সাহস সৈন্যদের নির্মম শীতকালীন অভিযানের মধ্য দিয়ে সফলভাবে পার করে নিয়ে গিয়েছিল।',
        category: 'Phrasal Verb',
        unit: 'Image 20 (image (20).jpg) - Phrasal Verbs (Continued)'
      },
      {
        id: 574,
        word: 'Catch at',
        ipa: '/kætʃ æt/',
        pos: 'phrase',
        meaning: 'সুযোগ আঁকড়ে ধরা, আকস্মিক গ্রহণ করা',
        synonyms: ['grasp at', 'seize', 'clutch at', 'snatch'],
        antonyms: ['reject', 'ignore', 'relinquish', 'let go'],
        raw_synonyms: 'grasp at, seize, clutch at, snatch',
        raw_antonyms: 'reject, ignore, relinquish, let go',
        sentence: 'Desperate to save his failing business, the merchant caught at every possible investment offer.',
        sentence_meaning: 'তার ব্যর্থ ব্যবসা বাঁচানোর জন্য মরিয়া হয়ে ব্যবসায়ী সম্ভাব্য প্রতিটি বিনিয়োগের সুযোগ আঁকড়ে ধরেছিলেন।',
        category: 'Phrasal Verb',
        unit: 'Image 20 (image (20).jpg) - Phrasal Verbs (Continued)'
      },
      {
        id: 575,
        word: 'Catch up',
        ipa: '/kætʃ ʌp/',
        pos: 'phrase',
        meaning: 'সমকক্ষ হওয়া, নাগাল ধরা, ঘাটতি পূরণ করা',
        synonyms: ['overtake', 'draw level with', 'reach', 'equalize'],
        antonyms: ['fall behind', 'lag', 'drop back', 'lose ground'],
        raw_synonyms: 'overtake, draw level with, reach, equalize',
        raw_antonyms: 'fall behind, lag, drop back, lose ground',
        sentence: 'Developing nations are investing heavily in technology to catch up with advanced economies.',
        sentence_meaning: 'উন্নয়নশীল দেশগুলো উন্নত অর্থনীতির সমকক্ষ হতে প্রযুক্তিতে প্রচুর বিনিয়োগ করছে।',
        category: 'Phrasal Verb',
        unit: 'Image 20 (image (20).jpg) - Phrasal Verbs (Continued)'
      }
    ]
  },
  {
    level_id: 116,
    title: 'Level 116: Appropriate Preposition',
    unit: 'Image 21 (image (21).jpg) - Appropriate Prepositions',
    category: 'Appropriate Preposition',
    items: [
      {
        id: 576,
        word: 'Accede to',
        ipa: '/əkˈsiːd tuː/',
        pos: 'prep',
        meaning: 'প্রস্তাব বা দাবিতে সম্মত বা রাজি হওয়া',
        synonyms: ['agree to', 'consent to', 'comply with', 'concur with'],
        antonyms: ['refuse', 'reject', 'decline', 'oppose'],
        raw_synonyms: 'agree to, consent to, comply with, concur with',
        raw_antonyms: 'refuse, reject, decline, oppose',
        sentence: 'The management finally decided to accede to the workers\' reasonable demands for salary increments.',
        sentence_meaning: 'কর্তৃপক্ষ অবশেষে বেতন বৃদ্ধির বিষয়ে শ্রমিকদের যৌক্তিক দাবিতে সম্মত হওয়ার সিদ্ধান্ত নিয়েছে।',
        category: 'Appropriate Preposition',
        unit: 'Image 21 (image (21).jpg) - Appropriate Prepositions'
      },
      {
        id: 577,
        word: 'Accompanied by',
        ipa: '/əˈkʌmpənid baɪ/',
        pos: 'prep',
        meaning: 'কারো সঙ্গী হওয়া, কোনো কিছুর সাথে ঘটা',
        synonyms: ['escorted by', 'joined by', 'attended by', 'coupled with'],
        antonyms: ['alone', 'unaccompanied', 'isolated', 'separated from'],
        raw_synonyms: 'escorted by, joined by, attended by, coupled with',
        raw_antonyms: 'alone, unaccompanied, isolated, separated from',
        sentence: 'The patient suffered from high fever accompanied by severe chills and body ache.',
        sentence_meaning: 'রোগী তীব্র শীতানুভূতি ও শরীর ব্যথার সাথে প্রচণ্ড জ্বরে ভুগছিলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 21 (image (21).jpg) - Appropriate Prepositions'
      },
      {
        id: 578,
        word: 'Accord to',
        ipa: '/əˈkɔːrd tuː/',
        pos: 'prep',
        meaning: 'কাউকে সম্মান বা অধিকার প্রদান করা',
        synonyms: ['grant to', 'bestow upon', 'award to', 'confer upon'],
        antonyms: ['withhold from', 'deny', 'deprive of', 'refuse'],
        raw_synonyms: 'grant to, bestow upon, award to, confer upon',
        raw_antonyms: 'withhold from, deny, deprive of, refuse',
        sentence: 'The dignitaries accorded a warm reception to the visiting foreign delegation.',
        sentence_meaning: 'বিশিষ্ট ব্যক্তিবর্গ সফররত বিদেশি প্রতিনিধিদলকে উষ্ণ সংবর্ধনা প্রদান করেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 21 (image (21).jpg) - Appropriate Prepositions'
      },
      {
        id: 579,
        word: 'Accord with',
        ipa: '/əˈkɔːrd wɪð/',
        pos: 'prep',
        meaning: 'কোনো তথ্যের সাথে মিল থাকা, সংগতিপূর্ণ হওয়া',
        synonyms: ['harmonize with', 'agree with', 'tally with', 'correspond to'],
        antonyms: ['conflict with', 'contradict', 'differ from', 'clash with'],
        raw_synonyms: 'harmonize with, agree with, tally with, correspond to',
        raw_antonyms: 'conflict with, contradict, differ from, clash with',
        sentence: 'The witness\'s testimony does not accord with the physical evidence found at the crime scene.',
        sentence_meaning: 'ঘটনাস্থলে পাওয়া বস্তুগত প্রমাণের সাথে সাক্ষীর জবানবন্দির মিল নেই।',
        category: 'Appropriate Preposition',
        unit: 'Image 21 (image (21).jpg) - Appropriate Prepositions'
      },
      {
        id: 580,
        word: 'Account for',
        ipa: '/əˈkaʊnt fɔːr/',
        pos: 'prep',
        meaning: 'জবাবদিহি করা, কারণ ব্যাখ্যা করা',
        synonyms: ['explain', 'justify', 'clarify', 'answer for'],
        antonyms: ['obscure', 'confuse', 'misrepresent', 'conceal'],
        raw_synonyms: 'explain, justify, clarify, answer for',
        raw_antonyms: 'obscure, confuse, misrepresent, conceal',
        sentence: 'The treasurer was asked to account for the financial discrepancies in the annual audit report.',
        sentence_meaning: 'বার্ষিক নিরীক্ষা প্রতিবেদনে আর্থিক অসঙ্গতির কারণ ব্যাখ্যা করার জন্য কোষাধ্যক্ষকে বলা হয়েছিল।',
        category: 'Appropriate Preposition',
        unit: 'Image 21 (image (21).jpg) - Appropriate Preposition'
      }
    ]
  },
  {
    level_id: 117,
    title: 'Level 117: Appropriate Preposition',
    unit: 'Image 21 (image (21).jpg) - Appropriate Prepositions',
    category: 'Appropriate Preposition',
    items: [
      {
        id: 581,
        word: 'Accountable to',
        ipa: '/əˈkaʊntəbl tuː/',
        pos: 'prep',
        meaning: 'কারো কাছে জবাবদিহি করতে বাধ্য বা দায়ী',
        synonyms: ['answerable to', 'responsible to', 'liable to', 'subject to'],
        antonyms: ['unaccountable', 'exempt from', 'immune', 'irresponsible'],
        raw_synonyms: 'answerable to, responsible to, liable to, subject to',
        raw_antonyms: 'unaccountable, exempt from, immune, irresponsible',
        sentence: 'Elected public officials are always accountable to the citizens they represent.',
        sentence_meaning: 'নির্বাচিত সরকারি কর্মকর্তারা সর্বদা তাদের প্রতিনিধিত্বকারী নাগরিকদের কাছে জবাবদিহি করতে বাধ্য।',
        category: 'Appropriate Preposition',
        unit: 'Image 21 (image (21).jpg) - Appropriate Prepositions'
      },
      {
        id: 582,
        word: 'Accused of',
        ipa: '/əˈkjuːzd ɒv/',
        pos: 'prep',
        meaning: 'কোনো অপরাধ বা অন্যায়ে অভিযুক্ত',
        synonyms: ['charged with', 'indicted for', 'blamed for', 'implicated in'],
        antonyms: ['acquitted of', 'cleared of', 'exonerated from', 'absolved of'],
        raw_synonyms: 'charged with, indicted for, blamed for, implicated in',
        raw_antonyms: 'acquitted of, cleared of, exonerated from, absolved of',
        sentence: 'The former accountant was formally accused of embezzlement by the board of directors.',
        sentence_meaning: 'পরিচালনা পর্ষদ কর্তৃক প্রাক্তন হিসাবরক্ষকের বিরুদ্ধে অর্থ আত্মসাতের আনুষ্ঠানিক অভিযোগ আনা হয়েছিল।',
        category: 'Appropriate Preposition',
        unit: 'Image 21 (image (21).jpg) - Appropriate Prepositions'
      },
      {
        id: 583,
        word: 'Accomplished in',
        ipa: '/əˈkʌmplɪʃt ɪn/',
        pos: 'prep',
        meaning: 'কোনো শিল্প বা বিদ্যায় দক্ষ বা নিপুণ',
        synonyms: ['skilled in', 'proficient in', 'expert in', 'adept in'],
        antonyms: ['inept in', 'unskilled in', 'clumsy in', 'amateurish in'],
        raw_synonyms: 'skilled in, proficient in, expert in, adept in',
        raw_antonyms: 'inept in, unskilled in, clumsy in, amateurish in',
        sentence: 'She is an accomplished pianist in classical music as well as a gifted painter.',
        sentence_meaning: 'তিনি শাস্ত্রীয় সঙ্গীতে একজন নিপুণ পিয়ানোবাদক এবং একই সাথে একজন প্রতিভাবান চিত্রশিল্পী।',
        category: 'Appropriate Preposition',
        unit: 'Image 21 (image (21).jpg) - Appropriate Prepositions'
      },
      {
        id: 584,
        word: 'Accustomed to',
        ipa: '/əˈkʌstəmd tuː/',
        pos: 'prep',
        meaning: 'কোনো পরিবেশ বা অভ্যাসে অভ্যস্ত',
        synonyms: ['used to', 'habituated to', 'familiar with', 'acclimatized to'],
        antonyms: ['unaccustomed to', 'unfamiliar with', 'unacquainted with', 'unused to'],
        raw_synonyms: 'used to, habituated to, familiar with, acclimatized to',
        raw_antonyms: 'unaccustomed to, unfamiliar with, unacquainted with, unused to',
        sentence: 'Living in the Arctic region, the indigenous people are accustomed to harsh sub-zero temperatures.',
        sentence_meaning: 'সুমেরু অঞ্চলে বসবাস করায় আদিবাসীরা শূন্যের নিচের তীব্র তাপমাত্রায় অভ্যস্ত।',
        category: 'Appropriate Preposition',
        unit: 'Image 21 (image (21).jpg) - Appropriate Prepositions'
      },
      {
        id: 585,
        word: 'Acquainted with',
        ipa: '/əˈkweɪntɪd wɪð/',
        pos: 'prep',
        meaning: 'কারো সাথে পরিচিত বা কোনো বিষয়ে অভিজ্ঞ ও জ্ঞাত',
        synonyms: ['familiar with', 'conversant with', 'informed about', 'conscious of'],
        antonyms: ['unacquainted with', 'unfamiliar with', 'ignorant of', 'stranger to'],
        raw_synonyms: 'familiar with, conversant with, informed about, conscious of',
        raw_antonyms: 'unacquainted with, unfamiliar with, ignorant of, stranger to',
        sentence: 'New employees should quickly become acquainted with the organization\'s safety policies.',
        sentence_meaning: 'নতুন কর্মীদের দ্রুত সংস্থার নিরাপত্তা নীতিমালার সাথে পরিচিত হওয়া উচিত।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      }
    ]
  },
  {
    level_id: 118,
    title: 'Level 118: Appropriate Preposition',
    unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)',
    category: 'Appropriate Preposition',
    items: [
      {
        id: 586,
        word: 'Acquiesce in',
        ipa: '/ˌækwiˈes ɪn/',
        pos: 'prep',
        meaning: 'নীরবে মেনে নেওয়া, মৌন সম্মতি দেওয়া',
        synonyms: ['consent to', 'agree to', 'concede to', 'comply with'],
        antonyms: ['protest against', 'dissent from', 'resist', 'reject'],
        raw_synonyms: 'consent to, agree to, concede to, comply with',
        raw_antonyms: 'protest against, dissent from, resist, reject',
        sentence: 'The committee members chose to acquiesce in the chairman\'s final proposal to avoid conflict.',
        sentence_meaning: 'দ্বন্দ্ব এড়াতে কমিটির সদস্যরা চেয়ারম্যানের চূড়ান্ত প্রস্তাবে মৌন সম্মতি জানানোর সিদ্ধান্ত নিয়েছিলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 587,
        word: 'Acquit of',
        ipa: '/əˈkwɪt ɒv/',
        pos: 'prep',
        meaning: 'অভিযোগ বা দোষ থেকে নির্দোষ ঘোষণা করা, খালাস দেওয়া',
        synonyms: ['absolve of', 'exonerate from', 'clear of', 'vindicate from'],
        antonyms: ['convict of', 'charge with', 'condemn for', 'sentence for'],
        raw_synonyms: 'absolve of, exonerate from, clear of, vindicate from',
        raw_antonyms: 'convict of, charge with, condemn for, sentence for',
        sentence: 'The jury acquitted the suspect of all charges due to a lack of incriminating evidence.',
        sentence_meaning: 'সন্দেহাতীত প্রমাণের অভাবে জুরি আসামিকে সমস্ত অভিযোগ থেকে বেকসুর খালাস দিয়েছিল।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 588,
        word: 'Adapted to',
        ipa: '/əˈdæptɪd tuː/',
        pos: 'prep',
        meaning: 'কোনো বিশেষ পরিবেশ বা কাজের উপযোগী বা মানানসই',
        synonyms: ['suited to', 'fitted for', 'adjusted to', 'appropriate for'],
        antonyms: ['unsuited to', 'ill-fitted for', 'inappropriate for', 'unadapted to'],
        raw_synonyms: 'suited to, fitted for, adjusted to, appropriate for',
        raw_antonyms: 'unsuited to, ill-fitted for, inappropriate for, unadapted to',
        sentence: 'Desert plants are uniquely adapted to survive in extremely dry and arid conditions.',
        sentence_meaning: 'মরুভূমির উদ্ভিদগুলো অত্যন্ত শুষ্ক ও অনাবৃষ্টির পরিবেশে বেঁচে থাকার জন্য অনন্যভাবে উপযোগী।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 589,
        word: 'Addicted to',
        ipa: '/əˈdɪktɪd tuː/',
        pos: 'prep',
        meaning: 'কোনো ক্ষতিকর অভ্যাস বা নেশায় মারাত্মকভাবে আসক্ত',
        synonyms: ['hooked on', 'dependent on', 'habituated to', 'obsessed with'],
        antonyms: ['free from', 'indifferent to', 'detached from', 'opposed to'],
        raw_synonyms: 'hooked on, dependent on, habituated to, obsessed with',
        raw_antonyms: 'free from, indifferent to, detached from, opposed to',
        sentence: 'Excessive screen time causes many teenagers to become addicted to online video games.',
        sentence_meaning: 'অতিরিক্ত স্ক্রিন টাইম অনেক কিশোর-কিশোরীকে অনলাইন ভিডিও গেমে আসক্ত করে তোলে।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 590,
        word: 'Adept in',
        ipa: '/əˈdept ɪn/',
        pos: 'prep',
        meaning: 'কোনো কাজে অত্যন্ত পারদর্শী বা দক্ষ',
        synonyms: ['proficient in', 'skilled in', 'expert in', 'dexterous in'],
        antonyms: ['clumsy in', 'inept in', 'amateur in', 'unskilled in'],
        raw_synonyms: 'proficient in, skilled in, expert in, dexterous in',
        raw_antonyms: 'clumsy in, inept in, amateur in, unskilled in',
        sentence: 'The senior programmer is adept in developing complex algorithms and machine learning models.',
        sentence_meaning: 'সিনিয়র প্রোগ্রামার জটিল অ্যালগরিদম এবং মেশিন লার্নিং মডেল তৈরিতে অত্যন্ত পারদর্শী।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      }
    ]
  },
  {
    level_id: 119,
    title: 'Level 119: Appropriate Preposition',
    unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)',
    category: 'Appropriate Preposition',
    items: [
      {
        id: 591,
        word: 'Add to',
        ipa: '/æd tuː/',
        pos: 'prep',
        meaning: 'কোনো কিছু বৃদ্ধি করা, বাড়িয়ে দেওয়া',
        synonyms: ['increase', 'augment', 'enhance', 'supplement'],
        antonyms: ['subtract from', 'diminish', 'reduce', 'lessen'],
        raw_synonyms: 'increase, augment, enhance, supplement',
        raw_antonyms: 'subtract from, diminish, reduce, lessen',
        sentence: 'The unforeseen delays only served to add to the immense stress of the project team.',
        sentence_meaning: 'অপ্রত্যাশিত বিলম্বগুলো প্রকল্প দলের প্রচণ্ড মানসিক চাপ আরও বাড়িয়ে দিয়েছিল।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 592,
        word: 'Adequate for',
        ipa: '/ˈædɪkwət fɔːr/',
        pos: 'prep',
        meaning: 'কোনো প্রয়োজনের জন্য যথেষ্ট বা পর্যাপ্ত হওয়া',
        synonyms: ['sufficient for', 'enough for', 'suitable for', 'ample for'],
        antonyms: ['inadequate for', 'insufficient for', 'deficient for', 'scant for'],
        raw_synonyms: 'sufficient for, enough for, suitable for, ample for',
        raw_antonyms: 'inadequate for, insufficient for, deficient for, scant for',
        sentence: 'The current food reserves are adequate for the displaced flood victims in the shelter.',
        sentence_meaning: 'আশ্রয়কেন্দ্রে থাকা বাস্তুচ্যুত বন্যা দুর্গতদের প্রয়োজনের জন্য বর্তমান খাদ্য মজুদ পর্যাপ্ত।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 593,
        word: 'Answer for',
        ipa: '/ˈɑːnsər fɔːr/',
        pos: 'prep',
        meaning: 'কোনো ভুল বা কৃতকর্মের জন্য জবাবদিহি করা বা দায়ী থাকা',
        synonyms: ['take responsibility for', 'be accountable for', 'atone for', 'vouch for'],
        antonyms: ['deny responsibility for', 'disown', 'evade', 'absolve'],
        raw_synonyms: 'take responsibility for, be accountable for, atone for, vouch for',
        raw_antonyms: 'deny responsibility for, disown, evade, absolve',
        sentence: 'Corrupt corporate executives must answer for their financial fraud in the court of law.',
        sentence_meaning: 'দুর্নীতিগ্রস্ত কর্পোরেট নির্বাহীদের অবশ্যই আদালতে তাদের আর্থিক জালিয়াতির জন্য জবাবদিহি করতে হবে।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 594,
        word: 'Apprised of',
        ipa: '/əˈpraɪzd ɒv/',
        pos: 'prep',
        meaning: 'কোনো বিষয়ে সম্পূর্ণ অবগত বা তথ্যপ্রাপ্ত',
        synonyms: ['informed of', 'notified of', 'briefed on', 'aware of'],
        antonyms: ['uninformed of', 'ignorant of', 'unaware of', 'blind to'],
        raw_synonyms: 'informed of, notified of, briefed on, aware of',
        raw_antonyms: 'uninformed of, ignorant of, unaware of, blind to',
        sentence: 'The prime minister was promptly apprised of the emerging border security crisis.',
        sentence_meaning: 'প্রধানমন্ত্রীকে দ্রুত উদীয়মান সীমান্ত নিরাপত্তা সংকট সম্পর্কে অবহিত করা হয়েছিল।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 595,
        word: 'Aptitude for',
        ipa: '/ˈæptɪtjuːd fɔːr/',
        pos: 'prep',
        meaning: 'কোনো বিষয়ে সহজাত প্রতিভা, স্বাভাবিক ঝোঁক বা দক্ষতা',
        synonyms: ['talent for', 'flair for', 'knack for', 'bent for'],
        antonyms: ['inability for', 'ineptitude for', 'dislike for', 'inaptitude for'],
        raw_synonyms: 'talent for, flair for, knack for, bent for',
        raw_antonyms: 'inability for, ineptitude for, dislike for, inaptitude for',
        sentence: 'From an early age, the prodigy demonstrated an extraordinary aptitude for mathematics.',
        sentence_meaning: 'ছোটবেলা থেকেই প্রতিভাবান শিশুটি গণিতে অসাধারণ সহজাত প্রতিভা প্রদর্শন করেছিল।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      }
    ]
  },
  {
    level_id: 120,
    title: 'Level 120: Appropriate Preposition',
    unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)',
    category: 'Appropriate Preposition',
    items: [
      {
        id: 596,
        word: 'Associated with',
        ipa: '/əˈsəʊʃieɪtɪd wɪð/',
        pos: 'prep',
        meaning: 'কারো সাথে বা কোনো কিছুর সাথে সংশ্লিষ্ট বা জড়িত',
        synonyms: ['connected with', 'linked to', 'related to', 'affiliated with'],
        antonyms: ['separated from', 'disconnected from', 'unrelated to', 'detached from'],
        raw_synonyms: 'connected with, linked to, related to, affiliated with',
        raw_antonyms: 'separated from, disconnected from, unrelated to, detached from',
        sentence: 'Smoking and a sedentary lifestyle are closely associated with an increased risk of heart disease.',
        sentence_meaning: 'ধূমপান এবং অলস জীবনযাপন হৃদরোগের ঝুঁকি বৃদ্ধির সাথে ঘনিষ্ঠভাবে সম্পর্কিত।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 597,
        word: 'Attend to',
        ipa: '/əˈtend tuː/',
        pos: 'prep',
        meaning: 'মনোযোগ দেওয়া, যত্ন নেওয়া বা সেবা করা',
        synonyms: ['pay attention to', 'care for', 'serve', 'look after'],
        antonyms: ['neglect', 'ignore', 'disregard', 'overlook'],
        raw_synonyms: 'pay attention to, care for, serve, look after',
        raw_antonyms: 'neglect, ignore, disregard, overlook',
        sentence: 'The dedicated nurse promptly attended to the urgent medical needs of incoming emergency patients.',
        sentence_meaning: 'নিবেদিতপ্রাণ নার্স অবিলম্বে জরুরি বিভাগে আসা রোগীদের জরুরি চিকিৎসার যত্ন নিয়েছিলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 598,
        word: 'Authority on',
        ipa: '/ɔːˈθɒrəti ɒn/',
        pos: 'prep',
        meaning: 'কোনো নির্দিষ্ট বিষয়ে প্রামাণ্য বিশেষজ্ঞ বা পণ্ডিত',
        synonyms: ['expert on', 'specialist in', 'master of', 'scholar on'],
        antonyms: ['novice in', 'amateur in', 'layman on', 'ignorant of'],
        raw_synonyms: 'expert on, specialist in, master of, scholar on',
        raw_antonyms: 'novice in, amateur in, layman on, ignorant of',
        sentence: 'Professor Rahman is widely recognized as a foremost authority on South Asian history.',
        sentence_meaning: 'অধ্যাপক রহমান দক্ষিণ এশিয়ার ইতিহাসের একজন শীর্ষস্থানীয় বিশেষজ্ঞ হিসেবে সর্বজনস্বীকৃত।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 599,
        word: 'Authority for',
        ipa: '/ɔːˈθɒrəti fɔːr/',
        pos: 'prep',
        meaning: 'কোনো কাজ করার আইনি বা দাপ্তরিক অধিকার বা অনুমতি',
        synonyms: ['authorization for', 'permission for', 'power for', 'sanction for'],
        antonyms: ['prohibition against', 'ban on', 'disallowance of', 'restriction on'],
        raw_synonyms: 'authorization for, permission for, power for, sanction for',
        raw_antonyms: 'prohibition against, ban on, disallowance of, restriction on',
        sentence: 'Only the executive director has the official authority for approving major budget disbursements.',
        sentence_meaning: 'শুধুমাত্র নির্বাহী পরিচালকের কাছেই প্রধান বাজেট বরাদ্দের অনুমোদনের সরকারি অধিকার রয়েছে।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      },
      {
        id: 600,
        word: 'Aware of',
        ipa: '/əˈweər ɒv/',
        pos: 'prep',
        meaning: 'কোনো বিষয় সম্পর্কে সচেতন বা অবগত',
        synonyms: ['conscious of', 'cognizant of', 'mindful of', 'informed of'],
        antonyms: ['unaware of', 'ignorant of', 'oblivious to', 'unconscious of'],
        raw_synonyms: 'conscious of, cognizant of, mindful of, informed of',
        raw_antonyms: 'unaware of, ignorant of, oblivious to, unconscious of',
        sentence: 'Every driver must remain constantly aware of surrounding traffic and road conditions.',
        sentence_meaning: 'প্রত্যেক চালককে চারপাশের ট্রাফিক এবং রাস্তার অবস্থা সম্পর্কে সর্বদা সচেতন থাকতে হবে।',
        category: 'Appropriate Preposition',
        unit: 'Image 22 (image (22).jpg) - Appropriate Prepositions (Continued)'
      }
    ]
  }
];

const targetDir = path.join(__dirname, '..', 'public', 'data', 'levels');
levels.forEach(lvl => {
  const filePath = path.join(targetDir, `level_${lvl.level_id}.json`);
  fs.writeFileSync(filePath, JSON.stringify(lvl, null, 2) + '\n', 'utf8');
  console.log(`Successfully generated: level_${lvl.level_id}.json`);
});
