import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const targetDir = path.join(__dirname, '..', 'public', 'data', 'levels');
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

const levelsData = [
  {
    level_id: 41,
    title: 'Level 41: Appropriate Preposition',
    unit: 'Image 6: Appropriate Prepositions',
    category: 'Appropriate Preposition',
    items: [
      {
        id: 201,
        word: 'According to',
        ipa: '/əˈkɔːrdɪŋ tuː/',
        pos: 'prep',
        meaning: 'অনুসারে, মতানুসারে',
        synonyms: ['in accordance with', 'as stated by', 'consistent with', 'conforming to'],
        antonyms: ['contrary to', 'in violation of', 'opposed to'],
        raw_synonyms: 'in accordance with, as stated by, consistent with, conforming to',
        raw_antonyms: 'contrary to, in violation of, opposed to',
        sentence: 'According to official meteorological reports, heavy rainfall is expected throughout the weekend.',
        sentence_meaning: 'সরকারি আবহাওয়া প্রতিবেদন অনুযায়ী, সপ্তাহান্তে ভারী বৃষ্টিপাত হওয়ার সম্ভাবনা রয়েছে।',
        category: 'Appropriate Preposition',
        unit: 'Image 6: Appropriate Prepositions'
      },
      {
        id: 202,
        word: 'Adjacent to',
        ipa: '/əˈdʒeɪsnt tuː/',
        pos: 'prep',
        meaning: 'সংলগ্ন, নিকটবর্তী',
        synonyms: ['adjoining', 'neighboring', 'bordering on', 'next to'],
        antonyms: ['distant from', 'remote from', 'far from'],
        raw_synonyms: 'adjoining, neighboring, bordering on, next to',
        raw_antonyms: 'distant from, remote from, far from',
        sentence: 'The modern hospital was constructed adjacent to the central botanical garden.',
        sentence_meaning: 'আধুনিক হাসপাতালটি কেন্দ্রীয় বোটানিক্যাল গার্ডেনের সংলগ্ন স্থানে নির্মাণ করা হয়েছিল।',
        category: 'Appropriate Preposition',
        unit: 'Image 6: Appropriate Prepositions'
      },
      {
        id: 203,
        word: 'Adapted from',
        ipa: '/əˈdæptɪd frəm/',
        pos: 'prep',
        meaning: 'কোনো উৎস থেকে গৃহীত বা রূপান্তরিত',
        synonyms: ['derived from', 'borrowed from', 'based on', 'modeled on'],
        antonyms: ['originated from', 'independent of', 'unrelated to'],
        raw_synonyms: 'derived from, borrowed from, based on, modeled on',
        raw_antonyms: 'originated from, independent of, unrelated to',
        sentence: 'The acclaimed theatrical play was adapted from a classic nineteenth-century Bengali novel.',
        sentence_meaning: 'প্রশংসিত নাট্যনাটকটি ঊনবিংশ শতাব্দীর একটি ধ্রুপদী বাংলা উপন্যাস থেকে রূপান্তর করা হয়েছিল।',
        category: 'Appropriate Preposition',
        unit: 'Image 6: Appropriate Prepositions'
      },
      {
        id: 204,
        word: 'Argue with',
        ipa: '/ˈɑːrɡjuː wɪð/',
        pos: 'prep',
        meaning: 'কারো সাথে তর্ক বা বিতর্ক করা',
        synonyms: ['quarrel with', 'dispute with', 'debate with', 'bicker with'],
        antonyms: ['agree with', 'concur with', 'harmonize with'],
        raw_synonyms: 'quarrel with, dispute with, debate with, bicker with',
        raw_antonyms: 'agree with, concur with, harmonize with',
        sentence: 'It is futile to argue with stubborn individuals who refuse to look at logical facts.',
        sentence_meaning: 'যৌক্তিক তথ্য দেখতে অস্বীকারকারী একগুঁয়ে ব্যক্তিদের সাথে তর্ক করা নিষ্ফল।',
        category: 'Appropriate Preposition',
        unit: 'Image 6: Appropriate Prepositions'
      },
      {
        id: 205,
        word: 'Answer to',
        ipa: '/ˈænsər tuː/',
        pos: 'prep',
        meaning: 'প্রশ্নের উত্তর দেওয়া / কারো কাছে জবাবদিহি করা',
        synonyms: ['reply to', 'respond to', 'be accountable to', 'answerable to'],
        antonyms: ['ignore', 'disregard', 'evade'],
        raw_synonyms: 'reply to, respond to, be accountable to, answerable to',
        raw_antonyms: 'ignore, disregard, evade',
        sentence: 'Public servants must answer to the citizenry regarding the utilization of state revenue.',
        sentence_meaning: 'রাষ্ট্রীয় রাজস্ব ব্যবহারের বিষয়ে সরকারি কর্মচারীদের নাগরিকদের কাছে জবাবদিহি করতে হবে।',
        category: 'Appropriate Preposition',
        unit: 'Image 6: Appropriate Prepositions'
      }
    ]
  },
  {
    level_id: 42,
    title: 'Level 42: Appropriate Preposition',
    unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1',
    category: 'Appropriate Preposition',
    items: [
      {
        id: 206,
        word: 'Agree with',
        ipa: '/əˈɡriː wɪð/',
        pos: 'prep',
        meaning: 'একমত হওয়া / উপযোগী হওয়া',
        synonyms: ['concur with', 'align with', 'side with', 'harmonize with'],
        antonyms: ['disagree with', 'dissent from', 'oppose', 'contradict'],
        raw_synonyms: 'concur with, align with, side with, harmonize with',
        raw_antonyms: 'disagree with, dissent from, oppose, contradict',
        sentence: 'I completely agree with your proposal to implement renewable energy across all branch offices.',
        sentence_meaning: 'সব শাখা কার্যালয়ে নবায়নযোগ্য শক্তি বাস্তবায়নের আপনার প্রস্তাবের সাথে আমি সম্পূর্ণ একমত।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 207,
        word: 'Angry with',
        ipa: '/ˈæŋɡri wɪð/',
        pos: 'prep',
        meaning: 'কারো প্রতি ক্রুদ্ধ হওয়া বা রাগ করা',
        synonyms: ['enraged with', 'furious with', 'irritated with', 'infuriated with'],
        antonyms: ['pleased with', 'delighted with', 'calm with'],
        raw_synonyms: 'enraged with, furious with, irritated with, infuriated with',
        raw_antonyms: 'pleased with, delighted with, calm with',
        sentence: 'The manager was angry with the supplier for repeatedly failing to meet agreed shipment deadlines.',
        sentence_meaning: 'নির্ধারিত শিপমেন্ট সময়সীমা পূরণে বারবার ব্যর্থ হওয়ায় সরবরাহকারীর ওপর ব্যবস্থাপক ক্রুদ্ধ ছিলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 208,
        word: 'Annoyed with',
        ipa: '/əˈnɔɪd wɪð/',
        pos: 'prep',
        meaning: 'কারো ওপর অসন্তুষ্ট বা বিরক্ত',
        synonyms: ['irritated with', 'vexed with', 'displeased with', 'bothered by'],
        antonyms: ['pleased with', 'content with', 'delighted with'],
        raw_synonyms: 'irritated with, vexed with, displeased with, bothered by',
        raw_antonyms: 'pleased with, content with, delighted with',
        sentence: 'She was visibly annoyed with her brother for borrowing her laptop without prior permission.',
        sentence_meaning: 'পূর্বানুমতি ছাড়া ল্যাপটপ নেওয়ার কারণে তিনি তাঁর ভাইয়ের ওপর দৃশ্যত বিরক্ত ছিলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 209,
        word: 'Argue with',
        ipa: '/ˈɑːrɡjuː wɪð/',
        pos: 'prep',
        meaning: 'কারো সাথে বিতর্ক বা ঝগড়া করা',
        synonyms: ['dispute with', 'debate with', 'altercate with', 'quarrel with'],
        antonyms: ['agree with', 'compromise with', 'concur with'],
        raw_synonyms: 'dispute with, debate with, altercate with, quarrel with',
        raw_antonyms: 'agree with, compromise with, concur with',
        sentence: 'Rather than argue with opposing counsel, the lawyer calmly presented concrete documentary evidence.',
        sentence_meaning: 'বিপক্ষ আইনজীবীর সাথে তর্ক করার পরিবর্তে, আইনজীবী শান্তভাবে অকাট্য প্রামাণ্য দলিল উপস্থাপন করলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 210,
        word: 'Associated with',
        ipa: '/əˈsoʊsiˌeɪtɪd wɪð/',
        pos: 'prep',
        meaning: 'সম্পর্কিত বা জড়িত',
        synonyms: ['connected with', 'linked to', 'affiliated with', 'allied with'],
        antonyms: ['unrelated to', 'disconnected from', 'isolated from', 'detached from'],
        raw_synonyms: 'connected with, linked to, affiliated with, allied with',
        raw_antonyms: 'unrelated to, disconnected from, isolated from, detached from',
        sentence: 'Severe air pollution is directly associated with rising incidences of respiratory disorders.',
        sentence_meaning: 'তীব্র বায়ু দূষণ সরাসরি শ্বাসযন্ত্রের রোগের বৃদ্ধির সাথে সম্পর্কিত।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      }
    ]
  },
  {
    level_id: 43,
    title: 'Level 43: Appropriate Preposition',
    unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1',
    category: 'Appropriate Preposition',
    items: [
      {
        id: 211,
        word: 'Begin with',
        ipa: '/bɪˈɡɪn wɪð/',
        pos: 'prep',
        meaning: 'কোনো কিছু দিয়ে সূচনা করা',
        synonyms: ['commence with', 'start with', 'initiate with', 'originate with'],
        antonyms: ['end with', 'conclude with', 'terminate with', 'finish with'],
        raw_synonyms: 'commence with, start with, initiate with, originate with',
        raw_antonyms: 'end with, conclude with, terminate with, finish with',
        sentence: 'Let us begin with a brief historical overview before examining the contemporary data.',
        sentence_meaning: 'সমসাময়িক তথ্য পরীক্ষার পূর্বে আসুন আমরা একটি সংক্ষিপ্ত ঐতিহাসিক বিবরণ দিয়ে শুরু করি।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 212,
        word: 'Bored with',
        ipa: '/bɔːrd wɪð/',
        pos: 'prep',
        meaning: 'কোনো কিছুতে একঘেয়েমি বা ক্লান্তি অনুভব করা',
        synonyms: ['weary of', 'tired of', 'fed up with', 'uninterested in'],
        antonyms: ['fascinated by', 'enthusiastic about', 'captivated by', 'excited about'],
        raw_synonyms: 'weary of, tired of, fed up with, uninterested in',
        raw_antonyms: 'fascinated by, enthusiastic about, captivated by, excited about',
        sentence: 'Children quickly grew bored with the repetitive video games and asked to play outdoors.',
        sentence_meaning: 'শিশুরা একঘেয়ে ভিডিও গেমে দ্রুত বিরক্ত হয়ে বাইরে খেলার জন্য অনুরোধ করল।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 213,
        word: 'Busy with',
        ipa: '/ˈbɪzi wɪð/',
        pos: 'prep',
        meaning: 'কোনো কাজে ব্যস্ত বা নিমগ্ন',
        synonyms: ['occupied with', 'engaged in', 'preoccupied with', 'absorbed in'],
        antonyms: ['idle from', 'free from', 'unoccupied with'],
        raw_synonyms: 'occupied with, engaged in, preoccupied with, absorbed in',
        raw_antonyms: 'idle from, free from, unoccupied with',
        sentence: 'The editorial team is currently busy with proofreading the final manuscript for publication.',
        sentence_meaning: 'সম্পাদকীয় দলটি বর্তমানে প্রকাশের জন্য চূড়ান্ত পাণ্ডুলিপি প্রুফরিডিংয়ে ব্যস্ত রয়েছে।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 214,
        word: 'Collide with',
        ipa: '/kəˈlaɪd wɪð/',
        pos: 'prep',
        meaning: 'কোনো কিছুর সাথে সজোরে ধাক্কা খাওয়া',
        synonyms: ['crash into', 'smash into', 'bump into', 'impact with'],
        antonyms: ['swerve clear of', 'avoid', 'bypass', 'miss'],
        raw_synonyms: 'crash into, smash into, bump into, impact with',
        raw_antonyms: 'swerve clear of, avoid, bypass, miss',
        sentence: 'The speeding delivery van collided with a stationary freight truck during the heavy downpour.',
        sentence_meaning: 'ভারী বৃষ্টির সময় দ্রুতগামী ডেলিভারি ভ্যানটি একটি স্থির মালবাহী ট্রাকের সাথে সজোরে ধাক্কা খায়।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 215,
        word: 'Compare with',
        ipa: '/kəmˈper wɪð/',
        pos: 'prep',
        meaning: 'সমজাতীয় বস্তুর তুলনা করা',
        synonyms: ['contrast with', 'measure against', 'match with', 'weigh against'],
        antonyms: ['differentiate from', 'separate from', 'dissociate from'],
        raw_synonyms: 'contrast with, measure against, match with, weigh against',
        raw_antonyms: 'differentiate from, separate from, dissociate from',
        sentence: 'If you compare with previous quarter earnings, this year\'s financial performance shows remarkable improvement.',
        sentence_meaning: 'পূর্ববর্তী প্রান্তিকের আয়ের সাথে তুলনা করলে চলতি বছরের আর্থিক ফলাফলে লক্ষণীয় উন্নতি দেখা যায়।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      }
    ]
  },
  {
    level_id: 44,
    title: 'Level 44: Appropriate Preposition',
    unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1',
    category: 'Appropriate Preposition',
    items: [
      {
        id: 216,
        word: 'Connection with',
        ipa: '/kəˈnekʃn wɪð/',
        pos: 'prep',
        meaning: 'কোনো কিছুর সাথে সম্পর্ক বা সংযোগ',
        synonyms: ['relation to', 'association with', 'tie with', 'link with'],
        antonyms: ['disconnection from', 'detachment from', 'isolation from'],
        raw_synonyms: 'relation to, association with, tie with, link with',
        raw_antonyms: 'disconnection from, detachment from, isolation from',
        sentence: 'Police interrogated the suspect regarding his alleged connection with the international smuggling ring.',
        sentence_meaning: 'আন্তর্জাতিক চোরাচালান চক্রের সাথে কথিত সংযোগের বিষয়ে পুলিশ সন্দেহভাজন ব্যক্তিকে জিজ্ঞাসাবাদ করে।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 217,
        word: 'Content with',
        ipa: '/kənˈtent wɪð/',
        pos: 'prep',
        meaning: 'কোনো কিছুতেই সন্তুষ্ট বা তৃপ্ত',
        synonyms: ['satisfied with', 'pleased with', 'gratified with', 'happy with'],
        antonyms: ['discontented with', 'dissatisfied with', 'unhappy with'],
        raw_synonyms: 'satisfied with, pleased with, gratified with, happy with',
        raw_antonyms: 'discontented with, dissatisfied with, unhappy with',
        sentence: 'He led a peaceful life in the countryside, content with modest means and good health.',
        sentence_meaning: 'তিনি সাধারণ জীবনোপায় ও সুস্বাস্থ্য নিয়ে সন্তুষ্ট থেকে গ্রামে একটি শান্তিময় জীবন যাপন করতেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 218,
        word: 'Cope with',
        ipa: '/koʊp wɪð/',
        pos: 'prep',
        meaning: 'কঠিন পরিস্থিতির মোকাবিলা করা বা সামলে ওঠা',
        synonyms: ['manage', 'handle', 'deal with', 'contend with'],
        antonyms: ['surrender to', 'succumb to', 'fail under', 'collapse under'],
        raw_synonyms: 'manage, handle, deal with, contend with',
        raw_antonyms: 'surrender to, succumb to, fail under, collapse under',
        sentence: 'Counselors helped traumatized disaster victims cope with severe emotional distress.',
        sentence_meaning: 'কাউন্সেলররা মানসিকভাবে বিপর্যস্ত দুর্যোগের শিকার ব্যক্তিদের তীব্র মানসিক কষ্ট কাটিয়ে উঠতে সাহায্য করেছিলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 219,
        word: 'Deal with',
        ipa: '/diːl wɪð/',
        pos: 'prep',
        meaning: 'মোকাবিলা করা বা মীমাংসা করা',
        synonyms: ['handle', 'address', 'tackle', 'manage'],
        antonyms: ['neglect', 'avoid', 'shirk', 'ignore'],
        raw_synonyms: 'handle, address, tackle, manage',
        raw_antonyms: 'neglect, avoid, shirk, ignore',
        sentence: 'Experienced managers know how to deal with customer grievances calmly and effectively.',
        sentence_meaning: 'অভিজ্ঞ পরিচালকরা জানেন কীভাবে গ্রাহকদের অভিযোগ শান্তভাবে এবং কার্যকরভাবে সমাধান করতে হয়।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 220,
        word: 'Delighted with',
        ipa: '/dɪˈlaɪtɪd wɪð/',
        pos: 'prep',
        meaning: 'কোনো কিছুতে অত্যন্ত আনন্দিত',
        synonyms: ['thrilled with', 'overjoyed at', 'ecstatic about', 'pleased with'],
        antonyms: ['disappointed with', 'dismayed by', 'displeased with'],
        raw_synonyms: 'thrilled with, overjoyed at, ecstatic about, pleased with',
        raw_antonyms: 'disappointed with, dismayed by, displeased with',
        sentence: 'The author was delighted with the overwhelmingly positive critical reviews of her new book.',
        sentence_meaning: 'লেখক তাঁর নতুন বইয়ের ব্যাপক ইতিবাচক সমালোচনামূলক পর্যালোচনা পেয়ে অত্যন্ত আনন্দিত হয়েছিলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      }
    ]
  },
  {
    level_id: 45,
    title: 'Level 45: Appropriate Preposition',
    unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1',
    category: 'Appropriate Preposition',
    items: [
      {
        id: 221,
        word: 'Discuss with',
        ipa: '/dɪˈskʌs wɪð/',
        pos: 'prep',
        meaning: 'কারো সাথে আলোচনা বা পরামর্শ করা',
        synonyms: ['confer with', 'consult with', 'deliberate with', 'talk over with'],
        antonyms: ['conceal from', 'withhold from', 'keep secret from'],
        raw_synonyms: 'confer with, consult with, deliberate with, talk over with',
        raw_antonyms: 'conceal from, withhold from, keep secret from',
        sentence: 'I will discuss with the senior consultant before finalizing the diagnostic surgical procedure.',
        sentence_meaning: 'ডায়াগনস্টিক অস্ত্রোপচার প্রক্রিয়া চূড়ান্ত করার আগে আমি জ্যেষ্ঠ পরামর্শকের সাথে আলোচনা করব।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 222,
        word: 'Familiar with',
        ipa: '/fəˈmɪliər wɪð/',
        pos: 'prep',
        meaning: 'কোনো বিষয়ে সুপরিচিত বা অভিজ্ঞ',
        synonyms: ['acquainted with', 'conversant with', 'versed in', 'knowledgeable about'],
        antonyms: ['unfamiliar with', 'ignorant of', 'unacquainted with', 'stranger to'],
        raw_synonyms: 'acquainted with, conversant with, versed in, knowledgeable about',
        raw_antonyms: 'unfamiliar with, ignorant of, unacquainted with, stranger to',
        sentence: 'Software developers must be familiar with modern version control systems like Git.',
        sentence_meaning: 'সফটওয়্যার ডেভেলপারদের অবশ্যই গিট (Git)-এর মতো আধুনিক সংস্করণ নিয়ন্ত্রণ ব্যবস্থার সাথে সুপরিচিত হতে হবে।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 223,
        word: 'Fed up with',
        ipa: '/ˌfed ˈʌp wɪð/',
        pos: 'prep',
        meaning: 'কোনো কিছুতে অতিষ্ঠ বা চরম বিরক্ত',
        synonyms: ['tired of', 'weary of', 'disgusted with', 'sick of'],
        antonyms: ['delighted with', 'happy with', 'fond of', 'enthusiastic about'],
        raw_synonyms: 'tired of, weary of, disgusted with, sick of',
        raw_antonyms: 'delighted with, happy with, fond of, enthusiastic about',
        sentence: 'Residents became thoroughly fed up with frequent unannounced power outages during hot summers.',
        sentence_meaning: 'তপ্ত গ্রীষ্মে ঘন ঘন অঘোষিত বিদ্যুৎ বিভ্রাটে এলাকাবাসী চরম অতিষ্ঠ হয়ে উঠেছিলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 224,
        word: 'Happy with',
        ipa: '/ˈhæpi wɪð/',
        pos: 'prep',
        meaning: 'কোনো ফলাফল বা জিনিসে সন্তুষ্ট বা খুশি',
        synonyms: ['pleased with', 'content with', 'gratified with', 'satisfied with'],
        antonyms: ['unhappy with', 'dissatisfied with', 'displeased with'],
        raw_synonyms: 'pleased with, content with, gratified with, satisfied with',
        raw_antonyms: 'unhappy with, dissatisfied with, displeased with',
        sentence: 'The client was exceptionally happy with the elegant interior redesign of his penthouse.',
        sentence_meaning: 'ক্লায়েন্ট তাঁর পেন্টহাউসের মার্জিত অভ্যন্তরীণ নতুন সজ্জায় অত্যন্ত সন্তুষ্ট ছিলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 225,
        word: 'Meet with',
        ipa: '/miːt wɪð/',
        pos: 'prep',
        meaning: 'কারো সাথে আনুষ্ঠানিকভাবে সাক্ষাৎ করা / বিপদের সম্মুখীন হওয়া',
        synonyms: ['confer with', 'encounter', 'experience', 'rendezvous with'],
        antonyms: ['avoid', 'evade', 'miss', 'dodge'],
        raw_synonyms: 'confer with, encounter, experience, rendezvous with',
        raw_antonyms: 'avoid, evade, miss, dodge',
        sentence: 'Trade envoys are scheduled to meet with senior economic ministers in Geneva next Tuesday.',
        sentence_meaning: 'বাণিজ্য দূতদের আগামী মঙ্গলবার জেনেভায় জ্যেষ্ঠ অর্থনৈতিক মন্ত্রীদের সাথে সাক্ষাতের কথা রয়েছে।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      }
    ]
  },
  {
    level_id: 46,
    title: 'Level 46: Appropriate Preposition',
    unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1',
    category: 'Appropriate Preposition',
    items: [
      {
        id: 226,
        word: 'Pleased with',
        ipa: '/pliːzd wɪð/',
        pos: 'prep',
        meaning: 'কোনো কাজ বা আচরণে সন্তুষ্ট',
        synonyms: ['gratified with', 'delighted with', 'satisfied with', 'happy with'],
        antonyms: ['displeased with', 'annoyed with', 'unhappy with'],
        raw_synonyms: 'gratified with, delighted with, satisfied with, happy with',
        raw_antonyms: 'displeased with, annoyed with, unhappy with',
        sentence: 'The school principal was immensely pleased with the students\' stellar academic performance.',
        sentence_meaning: 'শিক্ষার্থীদের চমৎকার একাডেমিক পারফরম্যান্সে বিদ্যালয়ের অধ্যক্ষ অত্যন্ত সন্তুষ্ট হয়েছিলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 227,
        word: 'Quarrel with',
        ipa: '/ˈkwɔːrəl wɪð/',
        pos: 'prep',
        meaning: 'কারো সাথে ঝগড়া বা বিবাদ করা',
        synonyms: ['argue with', 'squabble with', 'feud with', 'dispute with'],
        antonyms: ['agree with', 'harmonize with', 'make peace with'],
        raw_synonyms: 'argue with, squabble with, feud with, dispute with',
        raw_antonyms: 'agree with, harmonize with, make peace with',
        sentence: 'It is unwise to quarrel with neighbors over trivial boundary disputes.',
        sentence_meaning: 'তুচ্ছ সীমানা বিরোধ নিয়ে প্রতিবেশীদের সাথে ঝগড়া করা বুদ্ধিমানের কাজ নয়।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 228,
        word: 'Relationship with',
        ipa: '/rɪˈleɪʃnʃɪp wɪð/',
        pos: 'prep',
        meaning: 'কারো সাথে সম্পর্ক বা যোগাযোগ',
        synonyms: ['bond with', 'connection with', 'association with', 'rapport with'],
        antonyms: ['estrangement from', 'alienation from', 'hostility towards'],
        raw_synonyms: 'bond with, connection with, association with, rapport with',
        raw_antonyms: 'estrangement from, alienation from, hostility towards',
        sentence: 'Maintaining an open, trusting relationship with teenagers prevents many adolescent behavioral problems.',
        sentence_meaning: 'কিশোর-কিশোরীদের সাথে উন্মুক্ত ও বিশ্বাসযোগ্য সম্পর্ক বজায় রাখা বহু কিশোর আচরণগত সমস্যা রোধ করে।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 229,
        word: 'Satisfied with',
        ipa: '/ˈsætɪsfaɪd wɪð/',
        pos: 'prep',
        meaning: 'কোনো প্রাপ্তিতে পরিতৃপ্ত বা সন্তুষ্ট',
        synonyms: ['content with', 'pleased with', 'gratified with', 'fulfilled with'],
        antonyms: ['dissatisfied with', 'discontented with', 'unhappy with'],
        raw_synonyms: 'content with, pleased with, gratified with, fulfilled with',
        raw_antonyms: 'dissatisfied with, discontented with, unhappy with',
        sentence: 'The committee members were fully satisfied with the detailed financial audit report.',
        sentence_meaning: 'কমিটির সদস্যরা বিস্তারিত আর্থিক অডিট প্রতিবেদনে সম্পূর্ণ সন্তুষ্ট ছিলেন।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      },
      {
        id: 230,
        word: 'Sympathetic with',
        ipa: '/ˌsɪmpəˈθetɪk wɪð/',
        pos: 'prep',
        meaning: 'কারো দুঃখ-কষ্টে সহানুভূতিশীল',
        synonyms: ['compassionate toward', 'empathetic with', 'supportive of', 'kind to'],
        antonyms: ['unsympathetic to', 'callous toward', 'indifferent to', 'hostile to'],
        raw_synonyms: 'compassionate toward, empathetic with, supportive of, kind to',
        raw_antonyms: 'unsympathetic to, callous toward, indifferent to, hostile to',
        sentence: 'The community was deeply sympathetic with the families who lost homes in the river erosion.',
        sentence_meaning: 'নদীভাঙনে গৃহহীন হওয়া পরিবারগুলোর প্রতি এলাকাবাসী গভীরভাবে সহানুভূতিশীল ছিল।',
        category: 'Appropriate Preposition',
        unit: 'Image 7 (image (7).jpg) - Super Preposition Technique-1'
      }
    ]
  },
  {
    level_id: 47,
    title: 'Level 47: Word Transformation',
    unit: 'Image 8 (image (8).jpg) - Transformation of Word',
    category: 'Word Transformation',
    items: [
      {
        id: 231,
        word: 'Ability',
        ipa: '/əˈbɪləti/',
        pos: 'n',
        meaning: 'সামর্থ্য, সক্ষমতা',
        synonyms: ['capability', 'capacity', 'competence', 'aptitude'],
        antonyms: ['inability', 'incapacity', 'incompetence', 'weakness'],
        raw_synonyms: 'capability, capacity, competence, aptitude',
        raw_antonyms: 'inability, incapacity, incompetence, weakness',
        sentence: 'Her exceptional analytical ability enabled her to solve the complex mathematical puzzle quickly.',
        sentence_meaning: 'তাঁর ব্যতিক্রমী বিশ্লেষণাত্মক ক্ষমতা তাঁকে জটিল গাণিতিক ধাঁধাটি দ্রুত সমাধান করতে সক্ষম করেছিল।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 232,
        word: 'Acceptance',
        ipa: '/əkˈseptəns/',
        pos: 'n',
        meaning: 'গ্রহণযোগ্যতা, সম্মতি',
        synonyms: ['approval', 'agreement', 'reception', 'admission'],
        antonyms: ['rejection', 'denial', 'refusal', 'dismissal'],
        raw_synonyms: 'approval, agreement, reception, admission',
        raw_antonyms: 'rejection, denial, refusal, dismissal',
        sentence: 'The innovative scientific hypothesis gained widespread acceptance among nuclear physicists.',
        sentence_meaning: 'উদ্ভাবনী বৈজ্ঞানিক হাইপোথিসিসটি পারমাণবিক পদার্থবিজ্ঞানীদের মধ্যে ব্যাপক গ্রহণযোগ্যতা লাভ করেছিল।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 233,
        word: 'Acquisition',
        ipa: '/ˌækwɪˈzɪʃn/',
        pos: 'n',
        meaning: 'অর্জন, লাভ বা অধিগ্রহণ',
        synonyms: ['procurement', 'attainment', 'gain', 'possession'],
        antonyms: ['loss', 'forfeiture', 'deprivation', 'divestment'],
        raw_synonyms: 'procurement, attainment, gain, possession',
        raw_antonyms: 'loss, forfeiture, deprivation, divestment',
        sentence: 'Language acquisition occurs most naturally during the early formative years of childhood.',
        sentence_meaning: 'শৈশবের প্রাথমিক গঠনমূলক বছরগুলোতে ভাষা অর্জন সবচেয়ে প্রাকৃতিকভাবে ঘটে।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 234,
        word: 'Act',
        ipa: '/ækt/',
        pos: 'n',
        meaning: 'আইন, বিধান বা কর্মকাণ্ড',
        synonyms: ['statute', 'law', 'decree', 'deed'],
        antonyms: ['repeal', 'inactivity', 'omission', 'lawlessness'],
        raw_synonyms: 'statute, law, decree, deed',
        raw_antonyms: 'repeal, inactivity, omission, lawlessness',
        sentence: 'Parliament passed an emergency act to provide financial relief to flood victims.',
        sentence_meaning: 'বন্যাদুর্গতদের আর্থিক সহায়তা প্রদানের জন্য সংসদ একটি জরুরি আইন পাস করেছে।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 235,
        word: 'Admiration',
        ipa: '/ˌædməˈreɪʃn/',
        pos: 'n',
        meaning: 'প্রশংসা, শ্রদ্ধা',
        synonyms: ['esteem', 'respect', 'appreciation', 'veneration'],
        antonyms: ['contempt', 'disdain', 'scorn', 'disregard'],
        raw_synonyms: 'esteem, respect, appreciation, veneration',
        raw_antonyms: 'contempt, disdain, scorn, disregard',
        sentence: 'The courageous doctor earned the admiration and gratitude of the entire nation.',
        sentence_meaning: 'সাহসী চিকিৎসক সমগ্র জাতির প্রশংসা ও কৃতজ্ঞতা অর্জন করেছিলেন।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      }
    ]
  },
  {
    level_id: 48,
    title: 'Level 48: Word Transformation',
    unit: 'Image 8 (image (8).jpg) - Transformation of Word',
    category: 'Word Transformation',
    items: [
      {
        id: 236,
        word: 'Admission',
        ipa: '/ədˈmɪʃn/',
        pos: 'n',
        meaning: 'ভর্তি, প্রবেশাধিকার বা স্বীকারোক্তি',
        synonyms: ['entry', 'admittance', 'access', 'confession'],
        antonyms: ['exclusion', 'denial', 'prohibition', 'refusal'],
        raw_synonyms: 'entry, admittance, access, confession',
        raw_antonyms: 'exclusion, denial, prohibition, refusal',
        sentence: 'Competition for admission to prestigious engineering institutes remains exceptionally fierce.',
        sentence_meaning: 'মর্যাদাপূর্ণ ইঞ্জিনিয়ারিং ইনস্টিটিউটগুলোতে ভর্তির প্রতিযোগিতা অত্যন্ত তীব্র থাকে।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 237,
        word: 'Admittance',
        ipa: '/ədˈmɪtns/',
        pos: 'n',
        meaning: 'প্রবেশাধিকার, প্রবেশ অনুমতি',
        synonyms: ['access', 'entry', 'ingress', 'admission'],
        antonyms: ['prohibition', 'exclusion', 'ban', 'refusal'],
        raw_synonyms: 'access, entry, ingress, admission',
        raw_antonyms: 'prohibition, exclusion, ban, refusal',
        sentence: 'Signs posted outside the hazardous laboratory strictly warned against unauthorized admittance.',
        sentence_meaning: 'বিপজ্জনক পরীক্ষাগারের বাইরে লাগানো চিহ্নে অননুমোদিত প্রবেশের বিরুদ্ধে কঠোরভাবে সতর্ক করা হয়েছিল।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 238,
        word: 'Advice',
        ipa: '/ədˈvaɪs/',
        pos: 'n',
        meaning: 'উপদেশ, পরামর্শ',
        synonyms: ['guidance', 'counsel', 'recommendation', 'suggestion'],
        antonyms: ['misdirection', 'misguidance', 'discouragement'],
        raw_synonyms: 'guidance, counsel, recommendation, suggestion',
        raw_antonyms: 'misdirection, misguidance, discouragement',
        sentence: 'Following the veteran lawyer\'s sound advice saved the entrepreneur from costly litigation.',
        sentence_meaning: 'অভিজ্ঞ আইনজীবীর সঠিক পরামর্শ অনুসরণ করে উদ্যোক্তা ব্যয়বহুল মামলা থেকে রক্ষা পেয়েছিলেন।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 239,
        word: 'Analysis',
        ipa: '/əˈnæləsɪs/',
        pos: 'n',
        meaning: 'বিশ্লেষণ, পুঙ্খানুপুঙ্খ পরীক্ষা',
        synonyms: ['examination', 'evaluation', 'scrutiny', 'investigation'],
        antonyms: ['synthesis', 'generalization', 'overview'],
        raw_synonyms: 'examination, evaluation, scrutiny, investigation',
        raw_antonyms: 'synthesis, generalization, overview',
        sentence: 'A statistical analysis of the market data revealed surprising consumer buying trends.',
        sentence_meaning: 'বাজারের তথ্যের পরিসংখ্যানগত বিশ্লেষণ ভোক্তাদের কেনাকাটার আশ্চর্যজনক প্রবণতা প্রকাশ করেছে।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 240,
        word: 'Anger',
        ipa: '/ˈæŋɡər/',
        pos: 'n',
        meaning: 'রাগ, ক্রোধ',
        synonyms: ['fury', 'rage', 'wrath', 'indignation'],
        antonyms: ['calmness', 'placidity', 'patience', 'serenity'],
        raw_synonyms: 'fury, rage, wrath, indignation',
        raw_antonyms: 'calmness, placidity, patience, serenity',
        sentence: 'He struggled to control his surging anger during the unjust and biased debate.',
        sentence_meaning: 'অন্যায় এবং পক্ষপাতমূলক বিতর্কের সময় তিনি তাঁর তীব্র ক্ষোভ নিয়ন্ত্রণ করতে সংগ্রাম করেছিলেন।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      }
    ]
  },
  {
    level_id: 49,
    title: 'Level 49: Word Transformation',
    unit: 'Image 8 (image (8).jpg) - Transformation of Word',
    category: 'Word Transformation',
    items: [
      {
        id: 241,
        word: 'Appreciation',
        ipa: '/əˌpriːʃiˈeɪʃn/',
        pos: 'n',
        meaning: 'মূল্যায়ন, কৃতজ্ঞতা প্রকাশ',
        synonyms: ['gratitude', 'recognition', 'acknowledgment', 'admiration'],
        antonyms: ['depreciation', 'disparagement', 'ingratitude', 'criticism'],
        raw_synonyms: 'gratitude, recognition, acknowledgment, admiration',
        raw_antonyms: 'depreciation, disparagement, ingratitude, criticism',
        sentence: 'The community presented an award in sincere appreciation of her philanthropic work.',
        sentence_meaning: 'তাঁর মানবহিতৈষী কাজের আন্তরিক প্রশংসাস্বরূপ সমাজ তাঁকে একটি পুরস্কার প্রদান করেছে।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 242,
        word: 'Attention',
        ipa: '/əˈtenʃn/',
        pos: 'n',
        meaning: 'মনোযোগ, একাগ্রতা',
        synonyms: ['focus', 'concentration', 'alertness', 'mindfulness'],
        antonyms: ['inattention', 'distraction', 'neglect', 'carelessness'],
        raw_synonyms: 'focus, concentration, alertness, mindfulness',
        raw_antonyms: 'inattention, distraction, neglect, carelessness',
        sentence: 'The speaker commanded the undivided attention of the entire audience with her speech.',
        sentence_meaning: 'বক্তা তাঁর বক্তৃতার মাধ্যমে সমগ্র শ্রোতাদের অবিভক্ত মনোযোগ আকর্ষণ করেছিলেন।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 243,
        word: 'Availability',
        ipa: '/əˌveɪləˈbɪləti/',
        pos: 'n',
        meaning: 'প্রাপ্যতা, সহজলভ্যতা',
        synonyms: ['accessibility', 'readiness', 'obtainability', 'presence'],
        antonyms: ['scarcity', 'unavailability', 'absence', 'shortage'],
        raw_synonyms: 'accessibility, readiness, obtainability, presence',
        raw_antonyms: 'scarcity, unavailability, absence, shortage',
        sentence: 'The widespread availability of clean drinking water has reduced waterborne diseases drastically.',
        sentence_meaning: 'বিশুদ্ধ পানীয় জলের সহজলভ্যতা পানিবাহিত রোগকে ব্যাপকভাবে হ্রাস করেছে।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 244,
        word: 'Awe',
        ipa: '/ɔː/',
        pos: 'n',
        meaning: 'শ্রদ্ধামিশ্রিত ভয়, সম্ভ্রম বা বিস্ময়',
        synonyms: ['wonder', 'reverence', 'amazement', 'veneration'],
        antonyms: ['contempt', 'scorn', 'disregard', 'indifference'],
        raw_synonyms: 'wonder, reverence, amazement, veneration',
        raw_antonyms: 'contempt, scorn, disregard, indifference',
        sentence: 'Tourists stood in silent awe as the majestic northern lights illuminated the night sky.',
        sentence_meaning: 'মনোরম মেরুজ্যোতি রাতের আকাশকে আলোকিত করার সাথে সাথে পর্যটকরা নীরব বিস্ময়ে দাঁড়িয়ে রইলেন।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 245,
        word: 'Base',
        ipa: '/beɪs/',
        pos: 'n',
        meaning: 'ভিত্তি, বুনিয়াদ',
        synonyms: ['foundation', 'basis', 'bedrock', 'underpinning'],
        antonyms: ['top', 'apex', 'pinnacle', 'summit'],
        raw_synonyms: 'foundation, basis, bedrock, underpinning',
        raw_antonyms: 'top, apex, pinnacle, summit',
        sentence: 'A strong moral education forms the indispensable base of a civilized, progressive society.',
        sentence_meaning: 'একটি শক্তিশালী নৈতিক শিক্ষা একটি সভ্য ও প্রগতিশীল সমাজের অপরিহার্য ভিত্তি গঠন করে।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      }
    ]
  },
  {
    level_id: 50,
    title: 'Level 50: Word Transformation',
    unit: 'Image 8 (image (8).jpg) - Transformation of Word',
    category: 'Word Transformation',
    items: [
      {
        id: 246,
        word: 'Beauty',
        ipa: '/ˈbjuːti/',
        pos: 'n',
        meaning: 'সৌন্দর্য, রূপ',
        synonyms: ['attractiveness', 'elegance', 'loveliness', 'grace'],
        antonyms: ['ugliness', 'grotesqueness', 'unattractiveness', 'repulsiveness'],
        raw_synonyms: 'attractiveness, elegance, loveliness, grace',
        raw_antonyms: 'ugliness, grotesqueness, unattractiveness, repulsiveness',
        sentence: 'Poets throughout history have composed verses celebrating the ethereal beauty of pristine nature.',
        sentence_meaning: 'ইতিহাসজুড়ে কবিরা অমলিন প্রকৃতির অপার্থিব সৌন্দর্য উদযাপন করে কবিতা রচনা করেছেন।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 247,
        word: 'Belief',
        ipa: '/bɪˈliːf/',
        pos: 'n',
        meaning: 'বিশ্বাস, আস্থা',
        synonyms: ['conviction', 'faith', 'credence', 'trust'],
        antonyms: ['disbelief', 'skepticism', 'doubt', 'distrust'],
        raw_synonyms: 'conviction, faith, credence, trust',
        raw_antonyms: 'disbelief, skepticism, doubt, distrust',
        sentence: 'It is her steadfast belief that education is the most potent weapon against global poverty.',
        sentence_meaning: 'এটি তাঁর দৃঢ় বিশ্বাস যে শিক্ষা হলো বৈশ্বিক দারিদ্র্যের বিরুদ্ধে সবচেয়ে শক্তিশালী হাতিয়ার।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 248,
        word: 'Bitterness',
        ipa: '/ˈbɪtərnəs/',
        pos: 'n',
        meaning: 'তিক্ততা, বৈরিতা',
        synonyms: ['acrimony', 'hostility', 'resentment', 'sourness'],
        antonyms: ['sweetness', 'cordiality', 'warmth', 'friendliness'],
        raw_synonyms: 'acrimony, hostility, resentment, sourness',
        raw_antonyms: 'sweetness, cordiality, warmth, friendliness',
        sentence: 'Years of unresolved family conflict left deep traces of bitterness between the estranged siblings.',
        sentence_meaning: 'বছরের পর বছর ধরে অমীমাংসিত পারিবারিক দ্বন্দ্ব বিচ্ছিন্ন ভাইবোনদের মধ্যে তিক্ততার গভীর চিহ্ন রেখে গেছে।',
        category: 'Word Transformation',
        unit: 'Image 8 (image (8).jpg) - Transformation of Word'
      },
      {
        id: 249,
        word: 'Commentary',
        ipa: '/ˈkɑːmənteri/',
        pos: 'n',
        meaning: 'ধারাবিবরণী, ব্যাখ্যা বা মন্তব্য',
        synonyms: ['explanation', 'critique', 'analysis', 'interpretation'],
        antonyms: ['silence', 'omission', 'disregard'],
        raw_synonyms: 'explanation, critique, analysis, interpretation',
        raw_antonyms: 'silence, omission, disregard',
        sentence: 'The sports journalist provided insightful live commentary throughout the thrilling football final.',
        sentence_meaning: 'ক্রীড়া সাংবাদিক রোমাঞ্চকর ফুটবল ফাইনাল জুড়ে অন্তর্দৃষ্টিপূর্ণ সরাসরি ধারাবিবরণী প্রদান করেছিলেন।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      },
      {
        id: 250,
        word: 'Aesthetic',
        ipa: '/esˈθetɪk/',
        pos: 'adj',
        meaning: 'নান্দনিক, সৌন্দর্যচর্চামূলক',
        synonyms: ['artistic', 'visually pleasing', 'refined', 'tasteful'],
        antonyms: ['unaesthetic', 'tasteless', 'crude', 'unrefined'],
        raw_synonyms: 'artistic, visually pleasing, refined, tasteful',
        raw_antonyms: 'unaesthetic, tasteless, crude, unrefined',
        sentence: 'Modern architecture balances practical structural engineering with elegant aesthetic values.',
        sentence_meaning: 'আধুনিক স্থাপত্য ব্যবহারিক কাঠামোগত প্রকৌশলের সাথে মার্জিত নান্দনিক মূল্যের ভারসাম্য বজায় রাখে।',
        category: 'Vocabulary',
        unit: 'Image 9 (image (9).jpg) - Vocabulary (Unit:2)'
      }
    ]
  }
];

levelsData.forEach(lvl => {
  const filePath = path.join(targetDir, `level_${lvl.level_id}.json`);
  fs.writeFileSync(filePath, JSON.stringify(lvl, null, 2), 'utf-8');
  console.log(`Saved: ${filePath}`);
});

console.log('All 10 level files written successfully.');
