import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const targetDir = path.join(__dirname, '..', 'public', 'data', 'levels');

const levelsData = [
  {
    level_id: 91,
    title: "Level 91: Vocabulary",
    unit: "Memorizing Part",
    category: "Vocabulary",
    items: [
      {
        id: 451,
        word: "Banal",
        ipa: "/bəˈnɑːl/",
        pos: "adj",
        meaning: "গতানুগতিক, মামুলি, তুচ্ছ",
        synonyms: ["hackneyed", "trite", "commonplace", "vapid"],
        antonyms: ["original", "novel", "extraordinary", "stimulating"],
        raw_synonyms: "hackneyed, trite, commonplace, vapid",
        raw_antonyms: "original, novel, extraordinary, stimulating",
        sentence: "The film received negative reviews because of its banal dialogue and predictable ending.",
        sentence_meaning: "গতানুগতিক সংলাপ এবং অনুমানযোগ্য সমাপ্তির কারণে চলচ্চিত্রটি নেতিবাচক পর্যালোচনা পেয়েছিল।",
        category: "Vocabulary",
        unit: "Memorizing Part"
      },
      {
        id: 452,
        word: "Belie",
        ipa: "/bɪˈlaɪ/",
        pos: "v",
        meaning: "ভ্রান্ত ধারণা দেওয়া, মিথ্যা প্রমাণ করা",
        synonyms: ["contradict", "disprove", "misrepresent", "conceal"],
        antonyms: ["reveal", "affirm", "prove", "attest"],
        raw_synonyms: "contradict, disprove, misrepresent, conceal",
        raw_antonyms: "reveal, affirm, prove, attest",
        sentence: "Her calm facial expression belied the intense anxiety she was experiencing.",
        sentence_meaning: "তাঁর শান্ত মুখের অভিব্যক্তিটি তিনি যে তীব্র উদ্বেগের মধ্য দিয়ে যাচ্ছিলেন তা গোপন করে এক ভ্রান্ত ধারণা দিয়েছিল।",
        category: "Vocabulary",
        unit: "Memorizing Part"
      },
      {
        id: 453,
        word: "Beneficent",
        ipa: "/bɪˈnefɪsnt/",
        pos: "adj",
        meaning: "উদার, পরোপকারী, কল্যাণকামী",
        synonyms: ["charitable", "benevolent", "philanthropic", "generous"],
        antonyms: ["malicious", "harmful", "malevolent", "stingy"],
        raw_synonyms: "charitable, benevolent, philanthropic, generous",
        raw_antonyms: "malicious, harmful, malevolent, stingy",
        sentence: "The beneficent organization donated essential medicine and food to the disaster victims.",
        sentence_meaning: "উদার সংস্থাটি দুর্যোগকবলিত মানুষদের জন্য প্রয়োজনীয় ওষুধ ও খাদ্য দান করেছিল।",
        category: "Vocabulary",
        unit: "Memorizing Part"
      },
      {
        id: 454,
        word: "Bolster",
        ipa: "/ˈboʊlstər/",
        pos: "v",
        meaning: "সমর্থন দেওয়া, জোরদার করা, সাহস জোগানো",
        synonyms: ["strengthen", "reinforce", "boost", "support"],
        antonyms: ["undermine", "weaken", "discourage", "diminish"],
        raw_synonyms: "strengthen, reinforce, boost, support",
        raw_antonyms: "undermine, weaken, discourage, diminish",
        sentence: "The recent victory helped bolster the team's confidence ahead of the championship tournament.",
        sentence_meaning: "সাম্প্রতিক জয়টি চ্যাম্পিয়নশিপ টুর্নামেন্টের আগে দলের আত্মবিশ্বাস বাড়াতে সাহায্য করেছিল।",
        category: "Vocabulary",
        unit: "Memorizing Part"
      },
      {
        id: 455,
        word: "Bombastic",
        ipa: "/bɑːmˈbæstɪk/",
        pos: "adj",
        meaning: "আড়ম্বরপূর্ণ, বাগাড়ম্বরপূর্ণ",
        synonyms: ["pompous", "pretentious", "grandiose", "verbose"],
        antonyms: ["unpretentious", "humble", "modest", "restrained"],
        raw_synonyms: "pompous, pretentious, grandiose, verbose",
        raw_antonyms: "unpretentious, humble, modest, restrained",
        sentence: "His bombastic speech failed to impress the educated audience who valued substance over show.",
        sentence_meaning: "তাঁর বাগাড়ম্বরপূর্ণ ভাষণটি সেই শিক্ষিত শ্রোতাদের প্রভাবিত করতে ব্যর্থ হয়েছিল যারা প্রদর্শনের চেয়ে বিষয়বস্তুকে বেশি গুরুত্ব দিতেন।",
        category: "Vocabulary",
        unit: "Memorizing Part"
      }
    ]
  },
  {
    level_id: 92,
    title: "Level 92: Vocabulary",
    unit: "Memorizing Part",
    category: "Vocabulary",
    items: [
      {
        id: 456,
        word: "Booming",
        ipa: "/ˈbuːmɪŋ/",
        pos: "adj",
        meaning: "সমৃদ্ধিশালী, দ্রুত বর্ধনশীল",
        synonyms: ["flourishing", "thriving", "prospering", "expanding"],
        antonyms: ["declining", "shrinking", "slumping", "weakening"],
        raw_synonyms: "flourishing, thriving, prospering, expanding",
        raw_antonyms: "declining, shrinking, slumping, weakening",
        sentence: "The booming e-commerce market created unprecedented business opportunities for entrepreneurs.",
        sentence_meaning: "দ্রুত বর্ধনশীল ই-কমার্স বাজার উদ্যোক্তাদের জন্য অভূতপূর্ব ব্যবসায়িক সুযোগ তৈরি করেছে।",
        category: "Vocabulary",
        unit: "Memorizing Part"
      },
      {
        id: 457,
        word: "Baffle",
        ipa: "/ˈbæfl/",
        pos: "v",
        meaning: "বিভ্রান্ত করা, হতবুদ্ধি করা",
        synonyms: ["puzzle", "perplex", "bewilder", "confuse"],
        antonyms: ["clarify", "explain", "enlighten", "facilitate"],
        raw_synonyms: "puzzle, perplex, bewilder, confuse",
        raw_antonyms: "clarify, explain, enlighten, facilitate",
        sentence: "The complex mathematical equation seemed to baffle even the most experienced researchers.",
        sentence_meaning: "জটিল গাণিতিক সমীকরণটি এমনকি সবচেয়ে অভিজ্ঞ গবেষকদেরও বিভ্রান্ত ও হতবুদ্ধি করে তুলেছিল।",
        category: "Vocabulary",
        unit: "Memorizing Part"
      },
      {
        id: 458,
        word: "Bandit",
        ipa: "/ˈbændɪt/",
        pos: "n",
        meaning: "ডাকাত, দস্যু",
        synonyms: ["robber", "outlaw", "brigand", "highwayman"],
        antonyms: ["lawman", "guardian", "protector", "police"],
        raw_synonyms: "robber, outlaw, brigand, highwayman",
        raw_antonyms: "lawman, guardian, protector, police",
        sentence: "The armed bandit ambushed the merchant caravan travelling through the desolate valley.",
        sentence_meaning: "সশস্ত্র ডাকাতটি নির্জন উপত্যকা দিয়ে যাওয়া বণিক কাফেলাটিকে অতর্কিত আক্রমণ করেছিল।",
        category: "Vocabulary",
        unit: "Memorizing Part"
      },
      {
        id: 459,
        word: "Beatific",
        ipa: "/ˌbiːəˈtɪfɪk/",
        pos: "adj",
        meaning: "পরমানন্দময়, পরম সুখদায়ক",
        synonyms: ["blissful", "radiant", "joyful", "serene"],
        antonyms: ["miserable", "gloomy", "sorrowful", "dreadful"],
        raw_synonyms: "blissful, radiant, joyful, serene",
        raw_antonyms: "miserable, gloomy, sorrowful, dreadful",
        sentence: "The saint had a beatific smile that immediately comforted everyone who met him.",
        sentence_meaning: "সাধুর মুখে এমন এক পরমানন্দময় হাসি ছিল যা তাঁর সাথে দেখা করা সকলকে সঙ্গে সঙ্গে আশ্বস্ত ও শান্তি প্রদান করত।",
        category: "Vocabulary",
        unit: "Memorizing Part"
      },
      {
        id: 460,
        word: "Beauty",
        ipa: "/ˈbjuːti/",
        pos: "n",
        meaning: "সৌন্দর্য, লাবণ্য",
        synonyms: ["loveliness", "elegance", "attractiveness", "charm"],
        antonyms: ["ugliness", "hideousness", "unattractiveness", "repulsiveness"],
        raw_synonyms: "loveliness, elegance, attractiveness, charm",
        raw_antonyms: "ugliness, hideousness, unattractiveness, repulsiveness",
        sentence: "The serene beauty of the snow-covered Himalayan peaks left the travelers in awe.",
        sentence_meaning: "বরফে ঢাকা হিমালয়ের শৃঙ্গগুলোর শান্ত সৌন্দর্য পর্যটকদের মুগ্ধ ও বিস্মিত করেছিল।",
        category: "Vocabulary",
        unit: "Memorizing Part"
      }
    ]
  },
  {
    level_id: 93,
    title: "Level 93: Vocabulary",
    unit: "Vocabulary Table",
    category: "Vocabulary",
    items: [
      {
        id: 461,
        word: "Benign",
        ipa: "/bɪˈnaɪn/",
        pos: "adj",
        meaning: "সদয়, নিরীহ, ক্ষতিহীন",
        synonyms: ["gentle", "harmless", "kindly", "favorable"],
        antonyms: ["malignant", "harmful", "hostile", "vicious"],
        raw_synonyms: "gentle, harmless, kindly, favorable",
        raw_antonyms: "malignant, harmful, hostile, vicious",
        sentence: "Fortunately, the medical report confirmed that the growth was entirely benign.",
        sentence_meaning: "সৌভাগ্যবশত, মেডিকেল রিপোর্টে নিশ্চিত করা হয়েছে যে টিউমারটি সম্পূর্ণ ক্ষতিহীন ও নিরীহ ছিল।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 462,
        word: "Blasphemous",
        ipa: "/ˈblæsfəməs/",
        pos: "adj",
        meaning: "ধর্মনিন্দামূলক, ধর্মদ্রোহী",
        synonyms: ["sacrilegious", "profane", "irreverent", "impious"],
        antonyms: ["reverent", "respectful", "pious", "devout"],
        raw_synonyms: "sacrilegious, profane, irreverent, impious",
        raw_antonyms: "reverent, respectful, pious, devout",
        sentence: "The ancient council considered any insult against sacred traditions to be strictly blasphemous.",
        sentence_meaning: "প্রাচীন কাউন্সিল পবিত্র ঐতিহ্যের প্রতি যেকোনো অপমানকে কঠোরভাবে ধর্মনিন্দামূলক বলে মনে করত।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 463,
        word: "Blithe",
        ipa: "/blaɪð/",
        pos: "adj",
        meaning: "প্রফুল্ল, চিন্তামুক্ত, নিশ্চিন্ত",
        synonyms: ["cheerful", "carefree", "joyous", "lighthearted"],
        antonyms: ["morose", "gloomy", "sorrowful", "anxious"],
        raw_synonyms: "cheerful, carefree, joyous, lighthearted",
        raw_antonyms: "morose, gloomy, sorrowful, anxious",
        sentence: "He drove through the stormy night with a blithe indifference to the perilous road conditions.",
        sentence_meaning: "তিনি বিপজ্জনক রাস্তার পরিস্থিতির প্রতি এক নিশ্চিন্ত উদাসীনতা নিয়ে ঝোড়ো রাতের মধ্য দিয়ে গাড়ি চালিয়েছিলেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 464,
        word: "Boon",
        ipa: "/buːn/",
        pos: "n",
        meaning: "আশীর্বাদ, পরম প্রাপ্তি, বিশেষ সুবিধা",
        synonyms: ["blessing", "benefit", "godsend", "asset"],
        antonyms: ["curse", "bane", "misfortune", "disadvantage"],
        raw_synonyms: "blessing, benefit, godsend, asset",
        raw_antonyms: "curse, bane, misfortune, disadvantage",
        sentence: "The new bypass highway proved to be a great boon to daily commuters and freight drivers.",
        sentence_meaning: "নতুন বাইপাস মহাসড়কটি দৈনিক যাত্রী এবং পণ্যবাহী চালকদের জন্য একটি বড় আশীর্বাদ বলে প্রমাণিত হয়েছিল।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 465,
        word: "Breach",
        ipa: "/briːtʃ/",
        pos: "n",
        meaning: "লঙ্ঘন, ফাটল, ভঙ্গ",
        synonyms: ["violation", "infringement", "rupture", "break"],
        antonyms: ["compliance", "adherence", "repair", "union"],
        raw_synonyms: "violation, infringement, rupture, break",
        raw_antonyms: "compliance, adherence, repair, union",
        sentence: "Failing to deliver the goods on the promised date constituted a direct breach of contract.",
        sentence_meaning: "প্রতিশ্রুত তারিখে পণ্য সরবরাহ করতে ব্যর্থ হওয়া ছিল চুক্তির একটি সরাসরি লঙ্ঘন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      }
    ]
  },
  {
    level_id: 94,
    title: "Level 94: Vocabulary",
    unit: "Vocabulary Table",
    category: "Vocabulary",
    items: [
      {
        id: 466,
        word: "Brochure",
        ipa: "/broʊˈʃʊr/",
        pos: "n",
        meaning: "পুস্তিকা, প্রচারপত্র",
        synonyms: ["pamphlet", "leaflet", "booklet", "flyer"],
        antonyms: ["tome", "treatise", "volume", "manuscript"],
        raw_synonyms: "pamphlet, leaflet, booklet, flyer",
        raw_antonyms: "tome, treatise, volume, manuscript",
        sentence: "The tourist information center provided a colorful brochure outlining all historical landmarks.",
        sentence_meaning: "পর্যটন তথ্য কেন্দ্র সকল ঐতিহাসিক দর্শনীয় স্থান তুলে ধরে একটি রঙিন পুস্তিকা সরবরাহ করেছিল।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 467,
        word: "Bustle",
        ipa: "/ˈbʌsl/",
        pos: "n",
        meaning: "ব্যস্ততা, কোলাহল, চঞ্চলতা",
        synonyms: ["commotion", "activity", "flurry", "stir"],
        antonyms: ["calm", "tranquility", "stillness", "quiet"],
        raw_synonyms: "commotion, activity, flurry, stir",
        raw_antonyms: "calm, tranquility, stillness, quiet",
        sentence: "She enjoyed walking through the bustling market square early in the morning.",
        sentence_meaning: "তিনি খুব সকালে কর্মচঞ্চল ও কোলাহলপূর্ণ বাজার চত্বরের মধ্য দিয়ে হাঁটতে পছন্দ করতেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 468,
        word: "Bellicose",
        ipa: "/ˈbelɪkoʊs/",
        pos: "adj",
        meaning: "যুদ্ধংদেহী, মারমুখী, যুদ্ধকামী",
        synonyms: ["aggressive", "combative", "belligerent", "warlike"],
        antonyms: ["peaceful", "pacific", "conciliatory", "peaceable"],
        raw_synonyms: "aggressive, combative, belligerent, warlike",
        raw_antonyms: "peaceful, pacific, conciliatory, peaceable",
        sentence: "The diplomat warned that bellicose statements would derail peace talks between the neighboring nations.",
        sentence_meaning: "কূটনীতিক সতর্ক করেছিলেন যে যুদ্ধংদেহী বক্তব্য প্রতিবেশী দেশগুলোর মধ্যে শান্তি আলোচনাকে ব্যাহত করবে।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 469,
        word: "Concur",
        ipa: "/kənˈkɜːr/",
        pos: "v",
        meaning: "একমত হওয়া, সম্মতি দেওয়া",
        synonyms: ["agree", "coincide", "assent", "accord"],
        antonyms: ["disagree", "dissent", "differ", "oppose"],
        raw_synonyms: "agree, coincide, assent, accord",
        raw_antonyms: "disagree, dissent, differ, oppose",
        sentence: "The entire board of directors concurred with the CEO's proposal to expand into global markets.",
        sentence_meaning: "পরিচালক পর্ষদের সকল সদস্য বৈশ্বিক বাজারে সম্প্রসারণের বিষয়ে প্রধান নির্বাহীর প্রস্তাবের সাথে একমত হয়েছিলেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 470,
        word: "Cognitive",
        ipa: "/ˈkɑːɡnətɪv/",
        pos: "adj",
        meaning: "জ্ঞানসম্পর্কিত, বুদ্ধিবৃত্তিক, ধারণাগত",
        synonyms: ["intellectual", "mental", "perceptual", "cerebral"],
        antonyms: ["emotional", "instinctive", "physical", "noncognitive"],
        raw_synonyms: "intellectual, mental, perceptual, cerebral",
        raw_antonyms: "emotional, instinctive, physical, noncognitive",
        sentence: "Reading and continuous learning stimulate cognitive development throughout an individual's life.",
        sentence_meaning: "বই পড়া এবং অবিচ্ছিন্ন শিক্ষা একজন ব্যক্তির জীবনজুড়ে বুদ্ধিবৃত্তিক বিকাশকে উৎসাহিত করে।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      }
    ]
  },
  {
    level_id: 95,
    title: "Level 95: Vocabulary",
    unit: "Vocabulary Table",
    category: "Vocabulary",
    items: [
      {
        id: 471,
        word: "Counterpart",
        ipa: "/ˈkaʊntərpɑːrt/",
        pos: "n",
        meaning: "সমকক্ষ ব্যক্তি বা বস্তু, প্রতিরূপ",
        synonyms: ["equivalent", "peer", "counterweight", "match"],
        antonyms: ["opposite", "mismatch", "antithesis", "correlative"],
        raw_synonyms: "equivalent, peer, counterweight, match",
        raw_antonyms: "opposite, mismatch, antithesis, correlative",
        sentence: "The foreign minister met his European counterpart to sign the bilateral trade agreement.",
        sentence_meaning: "দ্বিপাক্ষিক বাণিজ্য চুক্তি স্বাক্ষরের জন্য পররাষ্ট্রমন্ত্রী তাঁর ইউরোপীয় সমকক্ষের সাথে বৈঠক করেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 472,
        word: "Crooked",
        ipa: "/ˈkrʊkɪd/",
        pos: "adj",
        meaning: "বাঁকা, অসৎ, কুটিল",
        synonyms: ["bent", "twisted", "dishonest", "devious"],
        antonyms: ["straight", "honest", "upright", "direct"],
        raw_synonyms: "bent, twisted, dishonest, devious",
        raw_antonyms: "straight, honest, upright, direct",
        sentence: "The auditor discovered that the company's crooked accountant had falsified financial records.",
        sentence_meaning: "নিরীক্ষক জানতে পেরেছিলেন যে কোম্পানির অসৎ হিসাবরক্ষক আর্থিক নথিপত্র জাল করেছিলেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 473,
        word: "Capable",
        ipa: "/ˈkeɪpəbl/",
        pos: "adj",
        meaning: "সক্ষম, দক্ষ, যোগ্য",
        synonyms: ["competent", "proficient", "skillful", "adept"],
        antonyms: ["incapable", "incompetent", "inept", "unskilled"],
        raw_synonyms: "competent, proficient, skillful, adept",
        raw_antonyms: "incapable, incompetent, inept, unskilled",
        sentence: "She is a highly capable engineer who can solve intricate software architecture problems quickly.",
        sentence_meaning: "তিনি একজন অত্যন্ত দক্ষ প্রকৌশলী যিনি জটিল সফটওয়্যার কাঠামোর সমস্যাগুলো দ্রুত সমাধান করতে পারেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 474,
        word: "Compulsory",
        ipa: "/kəmˈpʌlsəri/",
        pos: "adj",
        meaning: "বাধ্যতামূলক, অবশ্যকরণীয়",
        synonyms: ["mandatory", "obligatory", "imperative", "requisite"],
        antonyms: ["optional", "voluntary", "elective", "discretionary"],
        raw_synonyms: "mandatory, obligatory, imperative, requisite",
        raw_antonyms: "optional, voluntary, elective, discretionary",
        sentence: "Wearing a protective helmet is compulsory for all motorcycle riders on public roads.",
        sentence_meaning: "পাবলিক রাস্তায় সকল মোটরসাইকেল আরোহীর জন্য প্রতিরক্ষামূলক হেলমেট পরা বাধ্যতামূলক।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 475,
        word: "Conceal",
        ipa: "/kənˈsiːl/",
        pos: "v",
        meaning: "লুকানো, গোপন রাখা",
        synonyms: ["hide", "disguise", "mask", "camouflage"],
        antonyms: ["reveal", "disclose", "expose", "uncover"],
        raw_synonyms: "hide, disguise, mask, camouflage",
        raw_antonyms: "reveal, disclose, expose, uncover",
        sentence: "The spy used false documents to conceal his true identity from border officials.",
        sentence_meaning: "গোয়েন্দাটি সীমান্ত কর্মকর্তাদের কাছ থেকে নিজের আসল পরিচয় গোপন রাখতে জাল নথিপত্র ব্যবহার করেছিলেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      }
    ]
  },
  {
    level_id: 96,
    title: "Level 96: Vocabulary",
    unit: "Vocabulary Table",
    category: "Vocabulary",
    items: [
      {
        id: 476,
        word: "Contaminate",
        ipa: "/kənˈtæmɪneɪt/",
        pos: "v",
        meaning: "দূষিত করা, কলুষিত করা",
        synonyms: ["pollute", "taint", "defile", "corrupt"],
        antonyms: ["purify", "cleanse", "decontaminate", "sanitize"],
        raw_synonyms: "pollute, taint, defile, corrupt",
        raw_antonyms: "purify, cleanse, decontaminate, sanitize",
        sentence: "Improper disposal of chemical waste can contaminate drinking water supplies for entire communities.",
        sentence_meaning: "রাসায়নিক বর্জ্যের অনুচিত নিষ্কাশন সমগ্র জনপদের খাবার পানির সরবরাহকে দূষিত করতে পারে।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 477,
        word: "Convict",
        ipa: "/kənˈvɪkt/",
        pos: "v",
        meaning: "দোষী সাব্যস্ত করা, অপরাধী বলে রায় দেওয়া",
        synonyms: ["sentence", "condemn", "find guilty", "penalize"],
        antonyms: ["acquit", "absolve", "exonerate", "discharge"],
        raw_synonyms: "sentence, condemn, find guilty, penalize",
        raw_antonyms: "acquit, absolve, exonerate, discharge",
        sentence: "The court found enough forensic evidence to convict the suspect of armed robbery.",
        sentence_meaning: "সশস্ত্র ডাকাতির দায়ে সন্দেহভাজনকে দোষী সাব্যস্ত করার জন্য আদালত পর্যাপ্ত ফরেনসিক প্রমাণ পেয়েছিল।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 478,
        word: "Counterfeit",
        ipa: "/ˈkaʊntərfɪt/",
        pos: "adj",
        meaning: "জাল, নকল, কৃত্রিম",
        synonyms: ["fake", "bogus", "spurious", "forged"],
        antonyms: ["genuine", "authentic", "real", "legitimate"],
        raw_synonyms: "fake, bogus, spurious, forged",
        raw_antonyms: "genuine, authentic, real, legitimate",
        sentence: "Customs officers seized a massive shipment of counterfeit designer luxury watches.",
        sentence_meaning: "শুল্ক কর্মকর্তারা জাল বা নকল বিলাসবহুল ব্র্যান্ডের ঘড়ির একটি বিশাল চালান আটক করেছিলেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 479,
        word: "Cruel",
        ipa: "/ˈkruːəl/",
        pos: "adj",
        meaning: "নিষ্ঠুর, নির্দয়, পাষাণ",
        synonyms: ["brutal", "merciless", "ruthless", "callous"],
        antonyms: ["kind", "compassionate", "humane", "merciful"],
        raw_synonyms: "brutal, merciless, ruthless, callous",
        raw_antonyms: "kind, compassionate, humane, merciful",
        sentence: "It is cruel to treat captive animals with neglect and harsh punishment.",
        sentence_meaning: "বন্দী প্রাণীদের অবহেলা ও কঠোর শাস্তির সাথে রাখা অত্যন্ত নিষ্ঠুর।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 480,
        word: "Capricious",
        ipa: "/kəˈprɪʃəs/",
        pos: "adj",
        meaning: "খেয়ালি, খামখেয়ালী, ক্ষণে ক্ষণে পরিবর্তনশীল",
        synonyms: ["fickle", "whimsical", "unpredictable", "erratic"],
        antonyms: ["consistent", "stable", "steady", "predictable"],
        raw_synonyms: "fickle, whimsical, unpredictable, erratic",
        raw_antonyms: "consistent, stable, steady, predictable",
        sentence: "Investors grew weary of the capricious market trends that shifted wildly without warning.",
        sentence_meaning: "কোনো পূর্ব সতর্কবার্তা ছাড়াই মারাত্মকভাবে ওঠানামা করা খামখেয়ালী বাজারের গতিবিধিতে বিনিয়োগকারীরা ক্লান্ত হয়ে পড়েছিলেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      }
    ]
  },
  {
    level_id: 97,
    title: "Level 97: Vocabulary",
    unit: "Vocabulary Table",
    category: "Vocabulary",
    items: [
      {
        id: 481,
        word: "Chastise",
        ipa: "/tʃæˈstaɪz/",
        pos: "v",
        meaning: "কঠোর তিরস্কার করা, শাস্তি দেওয়া",
        synonyms: ["scold", "rebuke", "castigate", "reprimand"],
        antonyms: ["praise", "commend", "laud", "reward"],
        raw_synonyms: "scold, rebuke, castigate, reprimand",
        raw_antonyms: "praise, commend, laud, reward",
        sentence: "The manager had to chastise the employee for repeatedly arriving late to important team meetings.",
        sentence_meaning: "গুরুত্বপূর্ণ দলীয় মিটিংয়ে বারবার দেরি করে আসার কারণে ব্যবস্থাপককে কর্মচারীকে তিরস্কার করতে হয়েছিল।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 482,
        word: "Cacophonous",
        ipa: "/kæˈkɑːfənəs/",
        pos: "adj",
        meaning: "শ্রুতিকটু, কর্কশ শব্দযুক্ত, বেসুরো",
        synonyms: ["discordant", "harsh", "dissonant", "jarring"],
        antonyms: ["euphonious", "melodious", "harmonious", "tuneful"],
        raw_synonyms: "discordant, harsh, dissonant, jarring",
        raw_antonyms: "euphonious, melodious, harmonious, tuneful",
        sentence: "The construction site created a cacophonous din that disrupted the nearby quiet neighborhood.",
        sentence_meaning: "নির্মাণস্থলটি এমন এক কর্কশ ও শ্রুতিকটু শব্দের সৃষ্টি করেছিল যা কাছের শান্ত এলাকার পরিবেশকে বিঘ্নিত করেছিল।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 483,
        word: "Calamity",
        ipa: "/kəˈlæməti/",
        pos: "n",
        meaning: "মহাবিপর্যয়, চরম দুর্যোগ",
        synonyms: ["catastrophe", "disaster", "tragedy", "cataclysm"],
        antonyms: ["blessing", "godsend", "boon", "prosperity"],
        raw_synonyms: "catastrophe, disaster, tragedy, cataclysm",
        raw_antonyms: "blessing, godsend, boon, prosperity",
        sentence: "The sudden flash flood was a terrible calamity that devastated hundreds of farming villages.",
        sentence_meaning: "হঠাৎ আসা আকস্মিক বন্যাটি একটি ভয়াবহ মহাবিপর্যয় ছিল যা শত শত কৃষিপ্রধান গ্রামকে ধ্বংস করে দিয়েছিল।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 484,
        word: "Callous",
        ipa: "/ˈkæləs/",
        pos: "adj",
        meaning: "সহানুভূতিহীন, নির্দয়, পাষাণ",
        synonyms: ["unfeeling", "heartless", "indifferent", "apathetic"],
        antonyms: ["compassionate", "sympathetic", "caring", "sensitive"],
        raw_synonyms: "unfeeling, heartless, indifferent, apathetic",
        raw_antonyms: "compassionate, sympathetic, caring, sensitive",
        sentence: "The tyrant displayed a callous disregard for the basic human rights of his citizens.",
        sentence_meaning: "স্বৈরশাসক তাঁর নাগরিকদের মৌলিক মানবাধিকারের প্রতি সহানুভূতিহীন ও নিষ্ঠুর উদাসীনতা প্রদর্শন করেছিলেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 485,
        word: "Circumspect",
        ipa: "/ˈsɜːrkəmspekt/",
        pos: "adj",
        meaning: "সতর্ক, সুবিবেচক, সাবধানী",
        synonyms: ["cautious", "wary", "prudent", "vigilant"],
        antonyms: ["reckless", "rash", "careless", "imprudent"],
        raw_synonyms: "cautious, wary, prudent, vigilant",
        raw_antonyms: "reckless, rash, careless, imprudent",
        sentence: "In difficult negotiations, it is wise to remain circumspect and think before speaking.",
        sentence_meaning: "কঠিন সমঝোতা আলোচনার সময় সতর্ক থাকা এবং কথা বলার আগে ভেবে নেওয়া বুদ্ধিমানের কাজ।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      }
    ]
  },
  {
    level_id: 98,
    title: "Level 98: Vocabulary",
    unit: "Vocabulary Table",
    category: "Vocabulary",
    items: [
      {
        id: 486,
        word: "Clandestine",
        ipa: "/klænˈdestɪn/",
        pos: "adj",
        meaning: "গোপন, গুপ্ত",
        synonyms: ["secret", "covert", "furtive", "surreptitious"],
        antonyms: ["open", "public", "overt", "transparent"],
        raw_synonyms: "secret, covert, furtive, surreptitious",
        raw_antonyms: "open, public, overt, transparent",
        sentence: "The rebels held clandestine gatherings in underground bunkers to organize their movement.",
        sentence_meaning: "বিদ্রোহীরা তাদের আন্দোলন সংগঠিত করার জন্য ভূগর্ভস্থ বাঙ্কারে গোপন সমাবেশের আয়োজন করেছিল।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 487,
        word: "Coerce",
        ipa: "/koʊˈɜːrs/",
        pos: "v",
        meaning: "বাধ্য করা, বলপ্রয়োগ করা",
        synonyms: ["compel", "force", "intimidate", "pressurize"],
        antonyms: ["persuade", "cajole", "coax", "allow"],
        raw_synonyms: "compel, force, intimidate, pressurize",
        raw_antonyms: "persuade, cajole, coax, allow",
        sentence: "No employer should coerce workers into working overtime without adequate compensation.",
        sentence_meaning: "কোনো নিয়োগকর্তারই উচিত নয় শ্রমিকদের পর্যাপ্ত ক্ষতিপূরণ ছাড়া অতিরিক্ত সময় কাজ করতে বাধ্য করা।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 488,
        word: "Commence",
        ipa: "/kəˈmens/",
        pos: "v",
        meaning: "শুরু করা, আরম্ভ করা",
        synonyms: ["begin", "start", "initiate", "inaugurate"],
        antonyms: ["terminate", "conclude", "finish", "cease"],
        raw_synonyms: "begin, start, initiate, inaugurate",
        raw_antonyms: "terminate, conclude, finish, cease",
        sentence: "The annual international book fair will commence next Monday at the convention center.",
        sentence_meaning: "বার্ষিক আন্তর্জাতিক বইমেলা আগামী সোমবার কনভেনশন সেন্টারে শুরু হবে।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 489,
        word: "Commend",
        ipa: "/kəˈmend/",
        pos: "v",
        meaning: "প্রশংসা করা, তারিফ করা",
        synonyms: ["praise", "applaud", "laud", "extol"],
        antonyms: ["censure", "criticize", "reproach", "condemn"],
        raw_synonyms: "praise, applaud, laud, extol",
        raw_antonyms: "censure, criticize, reproach, condemn",
        sentence: "The principal commended the young volunteers for their dedicated service during the relief work.",
        sentence_meaning: "ত্রাণ কার্যক্রমে নিষ্ঠার সাথে সেবা দেওয়ার জন্য অধ্যক্ষ তরুণ স্বেচ্ছাসেবকদের ভূয়সী প্রশংসা করেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 490,
        word: "Converge",
        ipa: "/kənˈvɜːrdʒ/",
        pos: "v",
        meaning: "এক বিন্দুতে মিলিত হওয়া, জড়ো হওয়া",
        synonyms: ["assemble", "gather", "intersect", "unite"],
        antonyms: ["diverge", "scatter", "separate", "deviate"],
        raw_synonyms: "assemble, gather, intersect, unite",
        raw_antonyms: "diverge, scatter, separate, deviate",
        sentence: "Hundreds of researchers will converge in Geneva to attend the international medical summit.",
        sentence_meaning: "আন্তর্জাতিক চিকিৎসা সম্মেলনে যোগ দিতে শত শত গবেষক জেনেভায় একত্রিত হবেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      }
    ]
  },
  {
    level_id: 99,
    title: "Level 99: Vocabulary",
    unit: "Vocabulary Table",
    category: "Vocabulary",
    items: [
      {
        id: 491,
        word: "Convoluted",
        ipa: "/ˈkɑːnvəluːtɪd/",
        pos: "adj",
        meaning: "জটিল, প্যাঁচানো, দুর্বোধ্য",
        synonyms: ["intricate", "complex", "complicated", "tangled"],
        antonyms: ["simple", "straightforward", "clear", "direct"],
        raw_synonyms: "intricate, complex, complicated, tangled",
        raw_antonyms: "simple, straightforward, clear, direct",
        sentence: "The novel featured a convoluted plot with too many unexpected and confusing subplots.",
        sentence_meaning: "উপন্যাসটিতে প্রচুর অপ্রত্যাশিত এবং বিভ্রান্তিকর উপকাহিনি সংবলিত একটি জটিল ও প্যাঁচালো প্লট ছিল।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 492,
        word: "Craven",
        ipa: "/ˈkreɪvn/",
        pos: "adj",
        meaning: "কাপুরুষোচিত, চরম ভীরু",
        synonyms: ["cowardly", "fearful", "timorous", "pusillanimous"],
        antonyms: ["brave", "courageous", "valiant", "daring"],
        raw_synonyms: "cowardly, fearful, timorous, pusillanimous",
        raw_antonyms: "brave, courageous, valiant, daring",
        sentence: "Deserting your comrades during a crisis is considered a shameful and craven act.",
        sentence_meaning: "সংকটের সময় সহযোদ্ধাদের পরিত্যাগ করা একটি লজ্জাজনক এবং কাপুরুষোচিত কাজ হিসেবে বিবেচিত হয়।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 493,
        word: "Candid",
        ipa: "/ˈkændɪd/",
        pos: "adj",
        meaning: "অকপট, স্পষ্টবাদী, সরল",
        synonyms: ["frank", "honest", "outspoken", "forthright"],
        antonyms: ["deceitful", "guarded", "insincere", "evasive"],
        raw_synonyms: "frank, honest, outspoken, forthright",
        raw_antonyms: "deceitful, guarded, insincere, evasive",
        sentence: "The politician won public trust by giving candid answers to tough press questions.",
        sentence_meaning: "কঠিন প্রেস প্রশ্নের অকপট উত্তর দিয়ে রাজনীতিবিদ জনগণের আস্থা অর্জন করেছিলেন।",
        category: "Vocabulary",
        unit: "Vocabulary Table"
      },
      {
        id: 494,
        word: "Bite the bullet",
        ipa: "/baɪt ðə ˈbʊlɪt/",
        pos: "phrase",
        meaning: "কঠিন পরিস্থিতি সাহসের সাথে মেনে নেওয়া বা মোকাবিলা করা",
        synonyms: ["face the music", "brace oneself", "endure", "accept adversity"],
        antonyms: ["give up", "surrender", "evade", "retreat"],
        raw_synonyms: "face the music, brace oneself, endure, accept adversity",
        raw_antonyms: "give up, surrender, evade, retreat",
        sentence: "I hate going to the dentist, but with this toothache, I will just have to bite the bullet.",
        sentence_meaning: "আমি ডেন্টিস্টের কাছে যাওয়া অপছন্দ করি, কিন্তু এই দাঁতের ব্যথার কারণে আমাকে সাহসের সাথে পরিস্থিতি মেনে নিতেই হবে।",
        category: "Idiom",
        unit: "Idioms & Phrases Table"
      },
      {
        id: 495,
        word: "Beauty sleep",
        ipa: "/ˈbjuːti sliːp/",
        pos: "phrase",
        meaning: "পর্যাপ্ত ঘুম, স্বাস্থ্য ও সৌন্দর্যের জন্য প্রয়োজনীয় বিশ্রাম",
        synonyms: ["restful sleep", "sound sleep", "deep slumber", "restorative sleep"],
        antonyms: ["sleep deprivation", "insomnia", "sleeplessness", "wakefulness"],
        raw_synonyms: "restful sleep, sound sleep, deep slumber, restorative sleep",
        raw_antonyms: "sleep deprivation, insomnia, sleeplessness, wakefulness",
        sentence: "Make sure you get plenty of beauty sleep before your job interview tomorrow morning.",
        sentence_meaning: "নিশ্চিত করুন যে আগামীকাল সকালে আপনার চাকরির ইন্টারভিউয়ের আগে আপনি পর্যাপ্ত ঘুম ও বিশ্রাম নিচ্ছেন।",
        category: "Idiom",
        unit: "Idioms & Phrases Table"
      }
    ]
  },
  {
    level_id: 100,
    title: "Level 100: Idiom",
    unit: "Idioms & Phrases Table",
    category: "Idiom",
    items: [
      {
        id: 496,
        word: "Blow one's own horn",
        ipa: "/bloʊ wʌnz oʊn hɔːrn/",
        pos: "phrase",
        meaning: "নিজের গুণগান নিজে করা, নিজের ঢোল নিজে পেটানো",
        synonyms: ["brag", "boast", "show off", "self-promote"],
        antonyms: ["be humble", "understate", "be modest", "play down"],
        raw_synonyms: "brag, boast, show off, self-promote",
        raw_antonyms: "be humble, understate, be modest, play down",
        sentence: "A truly accomplished scholar never feels the need to blow their own horn.",
        sentence_meaning: "একজন প্রকৃত গুণী পণ্ডিত কখনই নিজের গুণগান নিজে করার প্রয়োজন বোধ করেন না।",
        category: "Idiom",
        unit: "Idioms & Phrases Table"
      },
      {
        id: 497,
        word: "Big gun",
        ipa: "/ˈbɪɡ ɡʌn/",
        pos: "phrase",
        meaning: "প্রভাবশালী বা গুরুত্বপূর্ণ ব্যক্তি, রাঘববোয়াল",
        synonyms: ["heavyweight", "VIP", "bigwig", "key figure"],
        antonyms: ["nobody", "nonentity", "subordinate", "underling"],
        raw_synonyms: "heavyweight, VIP, bigwig, key figure",
        raw_antonyms: "nobody, nonentity, subordinate, underling",
        sentence: "The government invited several big guns from the tech industry to advise on digital policy.",
        sentence_meaning: "সরকার ডিজিটাল নীতির বিষয়ে পরামর্শ দেওয়ার জন্য প্রযুক্তি শিল্পের বেশ কয়েকজন প্রভাবশালী ব্যক্তিকে আমন্ত্রণ জানিয়েছিল।",
        category: "Idiom",
        unit: "Idioms & Phrases Table"
      },
      {
        id: 498,
        word: "Bird's eye view",
        ipa: "/ˈbɜːrdz aɪ vjuː/",
        pos: "phrase",
        meaning: "সার্বিক দৃশ্য, ওপর থেকে সার্বিক রূপ বা ভাসাভাসি ধারণা",
        synonyms: ["overview", "aerial view", "panoramic view", "general summary"],
        antonyms: ["microscopic view", "detailed view", "worm's-eye view", "close-up"],
        raw_synonyms: "overview, aerial view, panoramic view, general summary",
        raw_antonyms: "microscopic view, detailed view, worm's-eye view, close-up",
        sentence: "The hot air balloon ride gave us a breathtaking bird's eye view of the green countryside.",
        sentence_meaning: "হট এয়ার বেলুন ভ্রমণ আমাদের সবুজ পল্লী অঞ্চলের একটি শ্বাসরুদ্ধকর মনোরম সার্বিক দৃশ্য দেখার সুযোগ করে দিয়েছিল।",
        category: "Idiom",
        unit: "Idioms & Phrases Table"
      },
      {
        id: 499,
        word: "Blow the cobwebs away",
        ipa: "/bloʊ ðə ˈkɒbwebz əˈweɪ/",
        pos: "phrase",
        meaning: "একঘেয়েমি ও ক্লান্তি ঝেড়ে ফেলে শরীর ও মনকে সতেজ করা",
        synonyms: ["refresh oneself", "clear one's head", "reinvigorate", "revitalize"],
        antonyms: ["stagnate", "tire oneself", "exhaust", "grow sluggish"],
        raw_synonyms: "refresh oneself, clear one's head, reinvigorate, revitalize",
        raw_antonyms: "stagnate, tire oneself, exhaust, grow sluggish",
        sentence: "Taking a brisk morning jog in the park will help blow the cobwebs away and get you ready for work.",
        sentence_meaning: "সকালে পার্কে দ্রুত জগিং করা একঘেয়েমি ঝেড়ে ফেলে মনকে সতেজ করতে এবং আপনাকে কাজের জন্য প্রস্তুত করতে সাহায্য করবে।",
        category: "Idiom",
        unit: "Idioms & Phrases Table"
      },
      {
        id: 500,
        word: "Bursting at the seams",
        ipa: "/ˈbɜːrstɪŋ æt ðə siːmz/",
        pos: "phrase",
        meaning: "লোকে লোকারণ্য, কানায় কানায় পূর্ণ",
        synonyms: ["packed", "overflowing", "jam-packed", "crowded"],
        antonyms: ["empty", "deserted", "vacant", "sparse"],
        raw_synonyms: "packed, overflowing, jam-packed, crowded",
        raw_antonyms: "empty, deserted, vacant, sparse",
        sentence: "During the festival season, the local marketplace was bursting at the seams with enthusiastic shoppers.",
        sentence_meaning: "উৎসবের মরসুমে স্থানীয় বাজারটি উৎসাহী ক্রেতাদের উপস্থিতিতে লোকে লোকারণ্য ও কানায় কানায় পূর্ণ ছিল।",
        category: "Idiom",
        unit: "Idioms & Phrases Table"
      }
    ]
  }
];

// Write level files
levelsData.forEach(lvl => {
  const fileName = `level_${lvl.level_id}.json`;
  const filePath = path.join(targetDir, fileName);
  fs.writeFileSync(filePath, JSON.stringify(lvl, null, 2), 'utf-8');
  console.log(`✅ Written ${fileName}`);
});

console.log('All 10 level files written successfully.');
